EXECUTE IMMEDIATE '
BEGIN
create or replace TABLE SIT.DM_INE_RESIDENCIA_ORIGEN_MLG (
	ID VARCHAR(20),
	LANGUAGE_KEY NUMBER(16,0),
	NIVEL_DES VARCHAR(200),
	LOAD_TIME TIMESTAMP_NTZ(9)
);

copy into SIT.DM_INE_RESIDENCIA_ORIGEN_MLG (ID,LANGUAGE_KEY,NIVEL_DES,LOAD_TIME)
FROM (select $1,$2,$3,to_timestamp_ntz(current_timestamp)  from ''@s3_stage/ine_dt/DM_INE_RESIDENCIA_ORIGEN_MLG_V2.csv'') file_format = ''csv_format_dm'' force= true on_error=''continue'';


create or replace TABLE SIT.DM_INE_RESIDENCIA_ORIGEN (
	ID VARCHAR(20),
	NOMBRE VARCHAR(16777216)
    );

copy into SIT.DM_INE_RESIDENCIA_ORIGEN (ID,NOMBRE)
FROM (select $1,$2  from ''@s3_stage/ine_dt/DM_INE_RESIDENCIA_ORIGEN_V1.csv'') file_format = ''csv_format_dm'' force= true on_error=''continue'';


create or replace TABLE SIT.DM_IVE_KPI_MASTER (
	KPI_KEY NUMBER(16,0),
	KPI_ID VARCHAR(100),
	KPI_DES VARCHAR(100),
	LOAD_TIME TIMESTAMP_NTZ(9)
);

copy into SIT.DM_IVE_KPI_MASTER (KPI_KEY,KPI_ID, KPI_DES, LOAD_TIME)
FROM (select $1,$2, $3, to_timestamp_ntz(current_timestamp)  from ''@s3_stage/ive_dt/DM_IVE_KPI_MASTER_V7.csv'') file_format = ''csv_format_dm'' force= true on_error=''continue'';

create or replace TABLE SIT.DM_IVE_KPI_MASTER_MLG (
	KPI_KEY NUMBER(16,0),
	LANGUAGE_KEY NUMBER(16,0),
	KPI_ID VARCHAR(100),
	KPI_DES VARCHAR(100),
	LOAD_TIME TIMESTAMP_NTZ(9)
);

copy into SIT.DM_IVE_KPI_MASTER_MLG (KPI_KEY,LANGUAGE_KEY,KPI_ID, KPI_DES, LOAD_TIME)
FROM (select $1,$2, $3, $4, to_timestamp_ntz(current_timestamp)  from ''@s3_stage/ive_dt/DM_IVE_KPI_MASTER_MLG_V8.csv'') file_format = ''csv_format_dm'' force= true on_error=''continue'';

create or replace TABLE PROCESS.RL_INE_OFERTA_ALOJAMIENTOS (
	FAMILIA VARCHAR(20),
    TABLA NUMBER(38,0),
	COD VARCHAR(20),
    COMUNIDADES_Y_CIUDADES_AUTONOMAS VARCHAR(50),
    CONCEPTO_TURISTICO VARCHAR(500),
    PROVINCIAS VARCHAR(50),
    PUNTOS_TURISTICOS VARCHAR(50),
    RESIDENCIA_ORIGEN VARCHAR(50),
    TIPO_DE_CATEGORIA VARCHAR(50),
    TIPO_DE_DATO VARCHAR(50),
	TIPO_DE_ESTABLECIMIENTO VARCHAR(50),
    TOTALES_TERRITORIALES VARCHAR(50),
    TOTAL_NACIONAL VARCHAR(24),
    ZONAS_TURISTICAS VARCHAR(77),
	LOAD_DATA_TIME TIMESTAMP_NTZ(9)
);

copy into PROCESS.RL_INE_OFERTA_ALOJAMIENTOS (FAMILIA,TABLA,COD,COMUNIDADES_Y_CIUDADES_AUTONOMAS,CONCEPTO_TURISTICO,PROVINCIAS,PUNTOS_TURISTICOS,RESIDENCIA_ORIGEN,TIPO_DE_CATEGORIA,TIPO_DE_DATO,TIPO_DE_ESTABLECIMIENTO,TOTALES_TERRITORIALES,TOTAL_NACIONAL,ZONAS_TURISTICAS, LOAD_DATA_TIME)
FROM (select $1,$2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, to_timestamp_ntz(current_timestamp)  from ''@s3_stage/ine_dt/RL_INE_OFERTA_ALOJAMIENTOS_V2.csv'') file_format = ''csv_format_dm'' force= true on_error=''continue'';

create or replace TABLE PROCESS.RL_INE_VIAJEROS_Y_PERNOCTACIONES (
    FAMILIA VARCHAR(20),
    TABLA NUMBER(38,0),
	COD VARCHAR(20),
    COMUNIDADES_Y_CIUDADES_AUTONOMAS VARCHAR(50),
	CONCEPTO_TURISTICO VARCHAR(50),
    PROVINCIAS VARCHAR(50),
	PUNTOS_TURISTICOS VARCHAR(50),
    RESIDENCIA_ORIGEN VARCHAR(50),
    TIPO_DE_CATEGORIA VARCHAR(50),
    TIPO_DE_DATO VARCHAR(50),
	TIPO_DE_ESTABLECIMIENTO VARCHAR(50),
	TOTALES_TERRITORIALES VARCHAR(50),
    TOTAL_NACIONAL VARCHAR(24),
    ZONAS_TURISTICAS VARCHAR(77),
	LOAD_DATA_TIME TIMESTAMP_NTZ(9)
);

copy into PROCESS.RL_INE_VIAJEROS_Y_PERNOCTACIONES (FAMILIA,TABLA,COD,COMUNIDADES_Y_CIUDADES_AUTONOMAS,CONCEPTO_TURISTICO,PROVINCIAS,PUNTOS_TURISTICOS,RESIDENCIA_ORIGEN,TIPO_DE_CATEGORIA,TIPO_DE_DATO,TIPO_DE_ESTABLECIMIENTO,git statuTOTALES_TERRITORIALES,TOTAL_NACIONAL,ZONAS_TURISTICAS, LOAD_DATA_TIME)
FROM (select $1,$2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, to_timestamp_ntz(current_timestamp)  from ''@s3_stage/ine_dt/RL_INE_VIAJEROS_Y_PERNOCTACIONES_V2.csv'') file_format = ''csv_format_dm'' force= true on_error=''continue'';

END;';