EXECUTE IMMEDIATE '
    BEGIN

CREATE OR REPLACE TABLE PROCESS.RL_INE_TURISMO_INTERNACIONAL (
    FAMILIA VARCHAR(20),
    TABLA NUMBER(38,0),
    COD VARCHAR(20),
    COMUNIDADES_Y_CIUDADES_AUTONOMAS VARCHAR(37),
    CONCEPTO_TURISTICO VARCHAR(62),
    CONTINENTES VARCHAR(32),
    PAISES VARCHAR(120),
    PROVINCIAS VARCHAR(37),
    RESIDENCIA_ORIGEN VARCHAR(39),
    TIPO_DE_DATO VARCHAR(39),
    TOTAL_NACIONAL VARCHAR(43),
    ZONAS_GEOGRAFICAS_DEL_RESTO_DEL_MUNDO VARCHAR(24),
    LOAD_DATA_TIME TIMESTAMP
);


COPY INTO PROCESS.RL_INE_TURISMO_INTERNACIONAL (FAMILIA, TABLA, COD, COMUNIDADES_Y_CIUDADES_AUTONOMAS, CONCEPTO_TURISTICO, CONTINENTES, PAISES, PROVINCIAS, RESIDENCIA_ORIGEN, TIPO_DE_DATO, TOTAL_NACIONAL, ZONAS_GEOGRAFICAS_DEL_RESTO_DEL_MUNDO, LOAD_DATA_TIME)
FROM (SELECT $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, TO_TIMESTAMP_NTZ(CURRENT_TIMESTAMP) FROM ''@s3_stage/ine_dt/RL_INE_TURISMO_INTERNACIONAL_V1.csv'')
FILE_FORMAT = ''csv_format_dm'' 
FORCE = TRUE 
ON_ERROR = ''CONTINUE'';

create or replace TABLE SIT.DM_GLB_COUNTRY (
	COUNTRY_KEY NUMBER(16,0),
	COUNTRY_ID VARCHAR(12),
	COUNTRY_DES VARCHAR(75),
	COUNTRY_NORM_DES VARCHAR(75),
	COUNTRY_SHORT_DES VARCHAR(15),
	COUNTRY_SHORT2_DES VARCHAR(15),
	COUNTRY_EUROSTAT_ID VARCHAR(15),
	ID_INE NUMBER(16,0),
	ID_ETR VARCHAR(15),
	ID_FRONTUR VARCHAR(15),
	ID_EGATUR VARCHAR(15),
    ID_EXPERIMENTAL VARCHAR(10),
	LOAD_TIME TIMESTAMP_NTZ(9)
);

COPY INTO SIT.DM_GLB_COUNTRY (COUNTRY_KEY, COUNTRY_ID, COUNTRY_DES, COUNTRY_NORM_DES, COUNTRY_SHORT_DES, COUNTRY_SHORT2_DES, COUNTRY_EUROSTAT_ID, ID_INE, ID_ETR, ID_FRONTUR, ID_EGATUR, ID_EXPERIMENTAL, LOAD_TIME)
FROM (SELECT $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, TO_TIMESTAMP_NTZ(CURRENT_TIMESTAMP) FROM ''@s3_stage/global/DM_GLB_COUNTRY_V11.csv'')
FILE_FORMAT = ''csv_format_dm'' 
FORCE = TRUE 
ON_ERROR = ''CONTINUE'';


create or replace TABLE PROCESS.RL_COUNTRY_TRANSLATOR (
	RAW_COUNTRY_DES VARCHAR(200),
	ORIGIN_DATA_ID VARCHAR(200),
	COUNTRY_DES VARCHAR(200),
	COUNTRY_ID VARCHAR(200),
	LOAD_TIME TIMESTAMP_LTZ(9) DEFAULT CURRENT_TIMESTAMP()
);

COPY INTO PROCESS.RL_COUNTRY_TRANSLATOR (RAW_COUNTRY_DES, ORIGIN_DATA_ID, COUNTRY_DES, COUNTRY_ID, LOAD_TIME)
FROM (SELECT $1, $2, $3, $4, TO_TIMESTAMP_NTZ(CURRENT_TIMESTAMP) FROM ''@s3_stage/flux_dt/RL_COUNTRY_TRANSLATOR_V2.csv'')
FILE_FORMAT = ''csv_format_dm'' 
FORCE = TRUE 
ON_ERROR = ''CONTINUE'';


create or replace TABLE SIT.DM_GLB_CITY (
	CITY_KEY NUMBER(16,0) NOT NULL,
	CITY_ID VARCHAR(5),
	CITY_CODE_ID VARCHAR(3),
	CITY_DES VARCHAR(75),
	CITY_NORM_DES VARCHAR(75),
	COMARCAL_REGION_KEY NUMBER(16,0),
	PROVINCE_KEY NUMBER(16,0),
	COUNTRY_KEY NUMBER(16,0),
	CITY_EUROSTAT_ID VARCHAR(15),
	CITY_IATA_ID VARCHAR(30),
	LATITUDE_NUM VARCHAR(30),
	LONGITUDE_NUM FLOAT,
	TOURIST_SPOT_FLG NUMBER(16,0),
	LOAD_TIME TIMESTAMP_NTZ(9),
	primary key (CITY_KEY)
);

COPY INTO SIT.DM_GLB_CITY (CITY_KEY, CITY_ID, CITY_CODE_ID, CITY_DES, CITY_NORM_DES, COMARCAL_REGION_KEY, PROVINCE_KEY, COUNTRY_KEY, CITY_EUROSTAT_ID, CITY_IATA_ID, LATITUDE_NUM, LONGITUDE_NUM, TOURIST_SPOT_FLG, LOAD_TIME)
FROM (SELECT $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, TO_TIMESTAMP_NTZ(CURRENT_TIMESTAMP) FROM ''@s3_stage/global/DM_GLB_CITY_V7.csv'')
FILE_FORMAT = ''csv_format_dm'' 
FORCE = TRUE 
ON_ERROR = ''CONTINUE'';

    END;';