
create or replace TABLE SIT.DM_IVE_KPI_MASTER (
	KPI_KEY NUMBER(16,0),
	KPI_ID VARCHAR(100),
	KPI_DES VARCHAR(100),
	LOAD_TIME TIMESTAMP_NTZ(9)
);

COPY INTO SIT.DM_IVE_KPI_MASTER (KPI_KEY, KPI_ID, KPI_DES, LOAD_TIME)
FROM (SELECT $1, $2, $3, TO_TIMESTAMP_NTZ(CURRENT_TIMESTAMP) FROM '@s3_stage/ive_dt/DM_IVE_KPI_MASTER_V6.csv')
FILE_FORMAT = 'csv_format_dm' 
FORCE = TRUE 
ON_ERROR = 'CONTINUE';


create or replace TABLE SIT.DM_IVE_KPI_MASTER_MLG (
	KPI_KEY NUMBER(16,0),
	LANGUAGE_KEY NUMBER(16,0),
	KPI_ID VARCHAR(100),
	KPI_DES VARCHAR(100),
	LOAD_TIME TIMESTAMP_NTZ(9)
);

COPY INTO SIT.DM_IVE_KPI_MASTER_MLG (KPI_KEY, LANGUAGE_KEY, KPI_ID, KPI_DES, LOAD_TIME)
FROM (SELECT $1, $2, $3, $4, TO_TIMESTAMP_NTZ(CURRENT_TIMESTAMP) FROM '@s3_stage/ive_dt/DM_IVE_KPI_MASTER_MLG_V7.csv')
FILE_FORMAT = 'csv_format_dm' 
FORCE = TRUE 
ON_ERROR = 'CONTINUE';