CREATE OR REPLACE TABLE DM_FWK_LOS_CAT_MLG(

     NAME VARCHAR2(30),

     ID NUMBER PRIMARY KEY,

     LANGUAGE_KEY NUMBER

)

;


INSERT INTO DM_FWK_LOS_CAT_MLG (NAME, ID, LANGUAGE_KEY) VALUES ('STAY', '1', '2');

INSERT INTO DM_FWK_LOS_CAT_MLG (NAME, ID, LANGUAGE_KEY) VALUES ('END_OF_TRIP', '2', '2');

INSERT INTO DM_FWK_LOS_CAT_MLG (NAME, ID, LANGUAGE_KEY) VALUES ('RETURN_HOME', '3', '2');

INSERT INTO DM_FWK_LOS_CAT_MLG (NAME, ID, LANGUAGE_KEY) VALUES ('DAY_TRIP', '4', '2');

INSERT INTO DM_FWK_LOS_CAT_MLG (NAME, ID, LANGUAGE_KEY) VALUES ('STARTING', '5', '2');

INSERT INTO DM_FWK_LOS_CAT_MLG (NAME, ID, LANGUAGE_KEY) VALUES ('PERMANENCIA', '1', '1');

INSERT INTO DM_FWK_LOS_CAT_MLG (NAME, ID, LANGUAGE_KEY) VALUES ('FIN DEL VIAJE', '2', '1');

INSERT INTO DM_FWK_LOS_CAT_MLG (NAME, ID, LANGUAGE_KEY) VALUES ('VUELTA A CASA', '3', '1');

INSERT INTO DM_FWK_LOS_CAT_MLG (NAME, ID, LANGUAGE_KEY) VALUES ('VIAJE DE UN DÍA', '4', '1');

INSERT INTO DM_FWK_LOS_CAT_MLG (NAME, ID, LANGUAGE_KEY) VALUES ('INICIO', '5', '1');

INSERT INTO DM_FWK_LOS_CAT_MLG (NAME, ID, LANGUAGE_KEY) VALUES ('PERMANENCIA', '1', '3');

INSERT INTO DM_FWK_LOS_CAT_MLG (NAME, ID, LANGUAGE_KEY) VALUES ('FINAL DEL VIATGE', '2', '3');

INSERT INTO DM_FWK_LOS_CAT_MLG (NAME, ID, LANGUAGE_KEY) VALUES ('TORNADA A CASA', '3', '3');

INSERT INTO DM_FWK_LOS_CAT_MLG (NAME, ID, LANGUAGE_KEY) VALUES ('VIATGE D''UN DIA', '4', '3');

INSERT INTO DM_FWK_LOS_CAT_MLG (NAME, ID, LANGUAGE_KEY) VALUES ('INICI', '5', '3');

COMMIT;


CREATE OR REPLACE TABLE DM_FWK_PAX_PROFILE_MLG(

     NAME VARCHAR2(30),

     ID NUMBER PRIMARY KEY,

     LANGUAGE_KEY NUMBER

)

;


INSERT INTO DM_FWK_PAX_PROFILE_MLG (NAME, ID, LANGUAGE_KEY) VALUES ('LEISURE', '1', '2');

INSERT INTO DM_FWK_PAX_PROFILE_MLG (NAME, ID, LANGUAGE_KEY) VALUES ('BUSINESS', '2', '2');

INSERT INTO DM_FWK_PAX_PROFILE_MLG (NAME, ID, LANGUAGE_KEY) VALUES ('VFR', '3', '2');

INSERT INTO DM_FWK_PAX_PROFILE_MLG (NAME, ID, LANGUAGE_KEY) VALUES ('GROUP', '4', '2');

INSERT INTO DM_FWK_PAX_PROFILE_MLG (NAME, ID, LANGUAGE_KEY) VALUES ('OCIO', '1', '1');

INSERT INTO DM_FWK_PAX_PROFILE_MLG (NAME, ID, LANGUAGE_KEY) VALUES ('NEGOCIO', '2', '1');

INSERT INTO DM_FWK_PAX_PROFILE_MLG (NAME, ID, LANGUAGE_KEY) VALUES ('VFR', '3', '1');

INSERT INTO DM_FWK_PAX_PROFILE_MLG (NAME, ID, LANGUAGE_KEY) VALUES ('GRUPO', '4', '1');

INSERT INTO DM_FWK_PAX_PROFILE_MLG (NAME, ID, LANGUAGE_KEY) VALUES ('OCI', '1', '3');

INSERT INTO DM_FWK_PAX_PROFILE_MLG (NAME, ID, LANGUAGE_KEY) VALUES ('NEGOCIS', '2', '3');

INSERT INTO DM_FWK_PAX_PROFILE_MLG (NAME, ID, LANGUAGE_KEY) VALUES ('VFR', '3', '3');

INSERT INTO DM_FWK_PAX_PROFILE_MLG (NAME, ID, LANGUAGE_KEY) VALUES ('GRUP', '4', '3');

COMMIT; 


CREATE OR REPLACE TABLE DM_FWK_SEARCH_LEVEL_MLG(

     NAME VARCHAR2(30),

     ID NUMBER PRIMARY KEY,

     LANGUAGE_KEY NUMBER

)

;

INSERT INTO DM_FWK_SEARCH_LEVEL_MLG (NAME, ID, LANGUAGE_KEY) VALUES ('CO_CO', '1', '2');

INSERT INTO DM_FWK_SEARCH_LEVEL_MLG (NAME, ID, LANGUAGE_KEY) VALUES ('CO_CI', '2', '2');

INSERT INTO DM_FWK_SEARCH_LEVEL_MLG (NAME, ID, LANGUAGE_KEY) VALUES ('CI_CO', '3', '2');

INSERT INTO DM_FWK_SEARCH_LEVEL_MLG (NAME, ID, LANGUAGE_KEY) VALUES ('CI_CI', '4', '2');

INSERT INTO DM_FWK_SEARCH_LEVEL_MLG (NAME, ID, LANGUAGE_KEY) VALUES ('CO_CO', '1', '1');

INSERT INTO DM_FWK_SEARCH_LEVEL_MLG (NAME, ID, LANGUAGE_KEY) VALUES ('CO_CI', '2', '1');

INSERT INTO DM_FWK_SEARCH_LEVEL_MLG (NAME, ID, LANGUAGE_KEY) VALUES ('CI_CO', '3', '1');

INSERT INTO DM_FWK_SEARCH_LEVEL_MLG (NAME, ID, LANGUAGE_KEY) VALUES ('CI_CI', '4', '1');

INSERT INTO DM_FWK_SEARCH_LEVEL_MLG (NAME, ID, LANGUAGE_KEY) VALUES ('CO_CO', '1', '3');

INSERT INTO DM_FWK_SEARCH_LEVEL_MLG (NAME, ID, LANGUAGE_KEY) VALUES ('CO_CI', '2', '3');

INSERT INTO DM_FWK_SEARCH_LEVEL_MLG (NAME, ID, LANGUAGE_KEY) VALUES ('CI_CO', '3', '3');

INSERT INTO DM_FWK_SEARCH_LEVEL_MLG (NAME, ID, LANGUAGE_KEY) VALUES ('CI_CI', '4', '3');

COMMIT; 


CREATE OR REPLACE TABLE DM_FWK_SEGMENT_TYPE(

     NAME VARCHAR2(30),

     ID NUMBER PRIMARY KEY

)

;


INSERT INTO DM_FWK_SEGMENT_TYPE (NAME, ID) VALUES ('OUTBOUND', '1');

INSERT INTO DM_FWK_SEGMENT_TYPE (NAME, ID) VALUES ('INBOUND', '2');

INSERT INTO DM_FWK_SEGMENT_TYPE (NAME, ID) VALUES ('RETURN', '3');

COMMIT; 


CREATE OR REPLACE TABLE DM_FWK_SEGMENT_TYPE_MLG(

     NAME VARCHAR2(30),

     ID NUMBER PRIMARY KEY,

     LANGUAGE_KEY NUMBER

)

;


INSERT INTO DM_FWK_SEGMENT_TYPE_MLG (NAME, ID, LANGUAGE_KEY) VALUES ('OUTBOUND', '1', '2');

INSERT INTO DM_FWK_SEGMENT_TYPE_MLG (NAME, ID, LANGUAGE_KEY) VALUES ('INBOUND', '2', '2');

INSERT INTO DM_FWK_SEGMENT_TYPE_MLG (NAME, ID, LANGUAGE_KEY) VALUES ('SALIDA', '1', '1');

INSERT INTO DM_FWK_SEGMENT_TYPE_MLG (NAME, ID, LANGUAGE_KEY) VALUES ('LLEGADA', '2', '1');

INSERT INTO DM_FWK_SEGMENT_TYPE_MLG (NAME, ID, LANGUAGE_KEY) VALUES ('SORTIDA', '1', '3');

INSERT INTO DM_FWK_SEGMENT_TYPE_MLG (NAME, ID, LANGUAGE_KEY) VALUES ('ARRIBADA', '2', '3');

INSERT INTO DM_FWK_SEGMENT_TYPE_MLG (NAME, ID, LANGUAGE_KEY) VALUES ('REGRESO', '3', '1');

INSERT INTO DM_FWK_SEGMENT_TYPE_MLG (NAME, ID, LANGUAGE_KEY) VALUES ('RETURN', '3', '2');

INSERT INTO DM_FWK_SEGMENT_TYPE_MLG (NAME, ID, LANGUAGE_KEY) VALUES ('TORNADA', '3', '3');

COMMIT;



CREATE OR REPLACE TABLE DM_FWK_TRIP_TYPE_MLG(

     NAME VARCHAR2(30),

     ID NUMBER PRIMARY KEY,

     LANGUAGE_KEY NUMBER

)

;



INSERT INTO DM_FWK_TRIP_TYPE_MLG (NAME, ID, LANGUAGE_KEY) VALUES ('ONEWAY', '1', '2');

INSERT INTO DM_FWK_TRIP_TYPE_MLG (NAME, ID, LANGUAGE_KEY) VALUES ('ROUNDTRIP', '2', '2');

INSERT INTO DM_FWK_TRIP_TYPE_MLG (NAME, ID, LANGUAGE_KEY) VALUES ('IDA', '1', '1');

INSERT INTO DM_FWK_TRIP_TYPE_MLG (NAME, ID, LANGUAGE_KEY) VALUES ('IDA Y VUELTA', '2', '1');

INSERT INTO DM_FWK_TRIP_TYPE_MLG (NAME, ID, LANGUAGE_KEY) VALUES ('IDA', '1', '3');

INSERT INTO DM_FWK_TRIP_TYPE_MLG (NAME, ID, LANGUAGE_KEY) VALUES ('IDA I TORNADA', '2', '3');

COMMIT; 



CREATE OR REPLACE TABLE DM_FWK_AIRPORT_MLG(
     AIRPORTIATACODE VARCHAR2(5),
     ID NUMBER PRIMARY KEY,
     AIRPORTICAOCODE VARCHAR2(5),
     TERMINALCODE VARCHAR2(10),
     AIRPORTNAME VARCHAR2(100),
     CITYCODE VARCHAR2(5),
     CITYNAME VARCHAR2(50),
     COUNTRYCODE VARCHAR2(3),
     REGIONCODE VARCHAR2(10),
     COUNTRYNAME VARCHAR2(100),
     ISO_CODE VARCHAR2(5),
     SUBCONTINENTCODE VARCHAR2(10),
     REGIONNAME VARCHAR2(100),
     SUBCONTINENTNAME VARCHAR2(100),
     CONTINENTCODE VARCHAR2(3),
     CONTINENTNAME VARCHAR2(100),
     ACTIVESTATUS NUMBER,
     AIRPORTLATITUDE FLOAT(),
     AIRPORTLONGITUDE FLOAT(),
     LOAD_TIME DATETIME,
     LANGUAGE_KEY NUMBER
)
;

copy into DM_FWK_AIRPORT_MLG (AIRPORTIATACODE, ID, AIRPORTICAOCODE, TERMINALCODE, AIRPORTNAME, CITYCODE, CITYNAME, COUNTRYCODE, REGIONCODE, COUNTRYNAME, ISO_CODE, SUBCONTINENTCODE, REGIONNAME, 
     SUBCONTINENTNAME, CONTINENTCODE, CONTINENTNAME, ACTIVESTATUS, AIRPORTLATITUDE, AIRPORTLONGITUDE, LOAD_TIME, LANGUAGE_KEY)
FROM(
   SELECT
       $1,
       $2,
       $3,
       $4,
       $5,
       $6,
       $7,
       $8,
       $9,
       $10,
       $11,
       $12,
       $13,
       $14,
       $15,
       $16,
       $17,
       $18,
       $19,
       to_timestamp_ntz(current_timestamp),
       $21
       FROM '@s3_stage/fwk_dt/DM_FWK_AIRPORT_MLG_V3.csv'
)
file_format = 'csv_format_dm'
on_error = 'continue';


CREATE OR REPLACE TABLE DM_REF_REGION_MLG(
     REGIONCODE VARCHAR2(10),
     ID NUMBER PRIMARY KEY,
     SUBCONTINENTCODE VARCHAR2(10),
     REGIONNAME VARCHAR2(100),
     SUBCONTINENTNAME VARCHAR2(100),
     CONTINENTCODE VARCHAR2(3),
     CONTINENTNAME VARCHAR2(100),
     ACTIVESTATUS NUMBER,
     LOAD_TIME DATETIME,
     LANGUAGE_KEY NUMBER
)
;

copy into DM_REF_REGION_MLG (REGIONCODE, ID, SUBCONTINENTCODE, REGIONNAME, SUBCONTINENTNAME, CONTINENTCODE, CONTINENTNAME, ACTIVESTATUS, LOAD_TIME, LANGUAGE_KEY)
FROM(
   SELECT
       $1,
       $2,
       $3,
       $4,
       $5,
       $6,
       $7,
       $8,
       to_timestamp_ntz(current_timestamp),
       $10,
       FROM '@s3_stage/dm_ref/DM_REF_REGION_MLG_V1.csv'
)
file_format = 'csv_format_dm'
on_error = 'continue';



CREATE OR REPLACE TABLE DM_REF_COUNTRY_MLG(
     COUNTRYCODE VARCHAR2(3),
     ID NUMBER PRIMARY KEY,
     REGIONCODE VARCHAR2(15),
     COUNTRYNAME VARCHAR2(100),
     ISO_CODE VARCHAR2(5),
     SUBCONTINENTCODE VARCHAR2(10),
     LOAD_TIME DATETIME, 
     LANGUAGE_KEY NUMBER
)
;

copy into DM_REF_COUNTRY_MLG (COUNTRYCODE, ID, REGIONCODE, COUNTRYNAME, ISO_CODE, SUBCONTINENTCODE, LOAD_TIME, LANGUAGE_KEY)
FROM(
   SELECT
       $1,
       $2,
       $3,
       $4,
       $5,
       $6,
       to_timestamp_ntz(current_timestamp),
       $8,
       FROM '@s3_stage/dm_ref/DM_REF_COUNTRY_MLG_V3.csv'
)
file_format = 'csv_format_dm'
on_error = 'continue';


create or replace TABLE SIT.DM_REF_CITY_MLG (
     CITYCODE VARCHAR(15),
     ID NUMBER(38,0) NOT NULL,
     CITYNAME VARCHAR(50),
     COUNTRYCODE VARCHAR(3),
     REGIONCODE VARCHAR(10),
     COUNTRYNAME VARCHAR(100),
     ISO_CODE VARCHAR(5),
     SUBCONTINENTCODE VARCHAR(10),
     REGIONNAME VARCHAR(100),
     SUBCONTINENTNAME VARCHAR(100),
     CONTINENTCODE VARCHAR(3),
     CONTINENTNAME VARCHAR(100),
     ACTIVESTATUS NUMBER(38,0),
     LATITUDE_NUM FLOAT,
     LONGITUDE_NUM FLOAT,
     LANGUAGE_KEY NUMBER(38,0),
     LOAD_TIME TIMESTAMP_NTZ(9),
     primary key (ID)
);


COPY INTO SIT.DM_REF_CITY_MLG (CITYCODE, ID, CITYNAME, COUNTRYCODE, REGIONCODE, COUNTRYNAME, ISO_CODE, SUBCONTINENTCODE, REGIONNAME, SUBCONTINENTNAME, CONTINENTCODE, CONTINENTNAME, ACTIVESTATUS, LATITUDE_NUM, LONGITUDE_NUM, LANGUAGE_KEY, LOAD_TIME)
FROM (
    SELECT
        $1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7,
        $8,
        $9,
        $10,
        $11,
        $12,
        $13,
        TRY_TO_DOUBLE(REPLACE($14, ',', '.')),
        TRY_TO_DOUBLE(REPLACE($15, ',', '.')),
        $16,
        TO_TIMESTAMP_NTZ(CURRENT_TIMESTAMP)
    FROM '@s3_stage/dm_ref/DM_REF_CITY_MLG_V2.csv'
)
FILE_FORMAT = 'csv_format_dm'
ON_ERROR = 'continue';

CREATE OR REPLACE TABLE DM_FWK_SEARCH_DISTANCE_CAT(
     NAME VARCHAR2(10),
     ID NUMBER PRIMARY KEY
)
;

INSERT INTO DM_FWK_SEARCH_DISTANCE_CAT (NAME, ID) VALUES ('LONG', '1');

INSERT INTO DM_FWK_SEARCH_DISTANCE_CAT (NAME, ID) VALUES ('MEDIUM', '2');

INSERT INTO DM_FWK_SEARCH_DISTANCE_CAT (NAME, ID) VALUES ('SHORT', '3');

COMMIT; 



CREATE OR REPLACE TABLE DM_FWK_SEARCH_DISTANCE_CAT_MLG(
     NAME VARCHAR2(30),
     ID NUMBER PRIMARY KEY,
     LANGUAGE_KEY NUMBER
)
;

INSERT INTO DM_FWK_SEARCH_DISTANCE_CAT_MLG (NAME, ID, LANGUAGE_KEY) VALUES ('Long distance', '1', '2');

INSERT INTO DM_FWK_SEARCH_DISTANCE_CAT_MLG (NAME, ID, LANGUAGE_KEY) VALUES ('Medium distance', '2', '2');

INSERT INTO DM_FWK_SEARCH_DISTANCE_CAT_MLG (NAME, ID, LANGUAGE_KEY) VALUES ('Short distance', '3', '2');

INSERT INTO DM_FWK_SEARCH_DISTANCE_CAT_MLG (NAME, ID, LANGUAGE_KEY) VALUES ('Larga distancia', '1', '1');

INSERT INTO DM_FWK_SEARCH_DISTANCE_CAT_MLG (NAME, ID, LANGUAGE_KEY) VALUES ('Media distancia', '2', '1');

INSERT INTO DM_FWK_SEARCH_DISTANCE_CAT_MLG (NAME, ID, LANGUAGE_KEY) VALUES ('Corta distancia', '3', '1');

INSERT INTO DM_FWK_SEARCH_DISTANCE_CAT_MLG (NAME, ID, LANGUAGE_KEY) VALUES ('Llarga distancia', '1', '3');

INSERT INTO DM_FWK_SEARCH_DISTANCE_CAT_MLG (NAME, ID, LANGUAGE_KEY) VALUES ('Mitja distancia', '2', '3');

INSERT INTO DM_FWK_SEARCH_DISTANCE_CAT_MLG (NAME, ID, LANGUAGE_KEY) VALUES ('Curta distancia', '3', '3');

COMMIT; 


CREATE OR REPLACE TABLE DM_FWK_SEGMENT_TYPE(
     NAME VARCHAR2(30),
     ID NUMBER PRIMARY KEY
)
;

INSERT INTO DM_FWK_SEGMENT_TYPE (NAME, ID) VALUES ('OUTBOUND', '1');

INSERT INTO DM_FWK_SEGMENT_TYPE (NAME, ID) VALUES ('INBOUND', '2');

INSERT INTO DM_FWK_SEGMENT_TYPE (NAME, ID) VALUES ('RETURN', '3');

COMMIT; 

CREATE OR REPLACE TABLE DM_FWK_SEGMENT_TYPE_MLG(
     NAME VARCHAR2(30),
     ID NUMBER PRIMARY KEY,
     LANGUAGE_KEY NUMBER
)
;

INSERT INTO DM_FWK_SEGMENT_TYPE_MLG (NAME, ID, LANGUAGE_KEY) VALUES ('OUTBOUND', '1', '2');

INSERT INTO DM_FWK_SEGMENT_TYPE_MLG (NAME, ID, LANGUAGE_KEY) VALUES ('INBOUND', '2', '2');

INSERT INTO DM_FWK_SEGMENT_TYPE_MLG (NAME, ID, LANGUAGE_KEY) VALUES ('SALIDA', '1', '1');

INSERT INTO DM_FWK_SEGMENT_TYPE_MLG (NAME, ID, LANGUAGE_KEY) VALUES ('LLEGADA', '2', '1');

INSERT INTO DM_FWK_SEGMENT_TYPE_MLG (NAME, ID, LANGUAGE_KEY) VALUES ('SORTIDA', '1', '3');

INSERT INTO DM_FWK_SEGMENT_TYPE_MLG (NAME, ID, LANGUAGE_KEY) VALUES ('ARRIBADA', '2', '3');

INSERT INTO DM_FWK_SEGMENT_TYPE_MLG (NAME, ID, LANGUAGE_KEY) VALUES ('REGRESO', '3', '1');

INSERT INTO DM_FWK_SEGMENT_TYPE_MLG (NAME, ID, LANGUAGE_KEY) VALUES ('RETURN', '3', '2');

INSERT INTO DM_FWK_SEGMENT_TYPE_MLG (NAME, ID, LANGUAGE_KEY) VALUES ('TORNADA', '3', '3');

COMMIT; 










 
