EXECUTE IMMEDIATE '
    BEGIN

create or replace TABLE SIT.DM_FLX_ZONE (
	ZONE_KEY NUMBER(16,0),
	ZONE_ID VARCHAR(100),
	ZONE_DES VARCHAR(100),
	ZONE_TYPE_DES VARCHAR(100),
	KM2 FLOAT,
	LOAD_TIME TIMESTAMP_LTZ(9) DEFAULT CURRENT_TIMESTAMP()
);

	COPY INTO SIT.DM_FLX_ZONE (ZONE_KEY, ZONE_ID, ZONE_DES, ZONE_TYPE_DES, KM2, LOAD_TIME)
	FROM (SELECT $1, $2, $3, $4, $5, TO_TIMESTAMP_NTZ(CURRENT_TIMESTAMP) FROM '''@s3_stage/flux_dt/DM_FLX_ZONE_V5.csv''')
	FILE_FORMAT = '''csv_format_dm''' 
	FORCE = TRUE 
	ON_ERROR = '''CONTINUE''';

    END;';