/*

EXECUTE IMMEDIATE '
    BEGIN
		
		CREATE OR REPLACE TABLE STAGING.ST_FLX_DIARIO_2H(
		FECHA DATE NOT NULL,
		DIADELASEMANA VARCHAR2(10) NOT NULL,
		ORIGEN VARCHAR2(15) NOT NULL,
		ZONAOBSERVACION VARCHAR2(100) NOT NULL,
		CATEGORIADELVISITANTE VARCHAR2(30) NOT NULL,
		HORA VARCHAR2(15) NOT NULL,
		VOLUMEN NUMBER NOT NULL,
		FILE_NAME VARCHAR2(200) NOT NULL,
		LOAD_DATE DATE NOT NULL
		)
		;

        RETURN ''Create table STAGING.ST_FLX_DIARIO_2H'';

    END;
';

EXECUTE IMMEDIATE '
    BEGIN

		CREATE OR REPLACE TABLE STAGING.ST_FLX_DIARIO_2H_MUNICIPIO(
		FECHA DATE NOT NULL,
		DIADELASEMANA VARCHAR2(10) NOT NULL,
		ORIGEN VARCHAR2(15) NOT NULL,
		NOMBREMUNICIPIO VARCHAR2(200) NOT NULL,
		NOMBREPROVINCIA VARCHAR2(50) NOT NULL,
		ZONAOBSERVACION VARCHAR2(100) NOT NULL,
		CATEGORIADELVISITANTE VARCHAR2(30) NOT NULL,
		HORA VARCHAR2(15) NOT NULL,
		VOLUMEN NUMBER NOT NULL,
		FILE_NAME VARCHAR2(200) NOT NULL,
		LOAD_DATE DATE NOT NULL
		)
		;

        RETURN ''Create table STAGING.ST_FLX_DIARIO_2H_MUNICIPIO'';

    END;
';

EXECUTE IMMEDIATE '
    BEGIN

		CREATE OR REPLACE TABLE STAGING.ST_FLX_DIARIO_2H_NACIONALIDAD(
		FECHA DATE NOT NULL,
		DIADELASEMANA VARCHAR2(10) NOT NULL,
		ORIGEN VARCHAR2(15) NOT NULL,
		PAIS VARCHAR2(30) NOT NULL,
		ZONAOBSERVACION VARCHAR2(100) NOT NULL,
		CATEGORIADELVISITANTE VARCHAR2(30) NOT NULL,
		HORA VARCHAR2(15) NOT NULL,
		VOLUMEN NUMBER NOT NULL,
		FILE_NAME VARCHAR2(200) NOT NULL,
		LOAD_DATE DATE NOT NULL
		)
		;

        RETURN ''Create table STAGING.ST_FLX_DIARIO_2H_NACIONALIDAD'';

    END;
';		

EXECUTE IMMEDIATE '
    BEGIN

		CREATE OR REPLACE TABLE STAGING.ST_FLX_DIARIO(
		FECHA DATE NOT NULL,
		DIADELASEMANA VARCHAR2(10) NOT NULL,
		ORIGEN VARCHAR2(15) NOT NULL,
		ZONAOBSERVACION VARCHAR2(100) NOT NULL,
		CATEGORIADELVISITANTE VARCHAR2(30) NOT NULL,
		VOLUMEN NUMBER NOT NULL,
		FILE_NAME VARCHAR2(200) NOT NULL,
		LOAD_DATE DATE NOT NULL
		)
		;

        RETURN ''Create table STAGING.ST_FLX_DIARIO'';

    END;
';		

EXECUTE IMMEDIATE '
    BEGIN

		CREATE OR REPLACE TABLE STAGING.ST_FLX_DIARIO_EDAD(
		FECHA DATE NOT NULL,
		DIADELASEMANA VARCHAR2(10) NOT NULL,
		ORIGEN VARCHAR2(15) NOT NULL,
		EDAD VARCHAR2(10) NOT NULL,
		ZONAOBSERVACION VARCHAR2(100) NOT NULL,
		CATEGORIADELVISITANTE VARCHAR2(30) NOT NULL,
		VOLUMEN NUMBER NOT NULL,
		FILE_NAME VARCHAR2(200) NOT NULL,
		LOAD_DATE DATE NOT NULL
		)
		;

        RETURN ''Create table STAGING.ST_FLX_DIARIO_EDAD'';

    END;
';

EXECUTE IMMEDIATE '
    BEGIN

		CREATE OR REPLACE TABLE STAGING.ST_FLX_DIARIO_GENERO(
		FECHA DATE NOT NULL,
		DIADELASEMANA VARCHAR2(10) NOT NULL,
		ORIGEN VARCHAR2(15) NOT NULL,
		GENERO VARCHAR2(10) NOT NULL,
		ZONAOBSERVACION VARCHAR2(100) NOT NULL,
		CATEGORIADELVISITANTE VARCHAR2(30) NOT NULL,
		VOLUMEN NUMBER NOT NULL,
		FILE_NAME VARCHAR2(200) NOT NULL,
		LOAD_DATE DATE NOT NULL
		)
		;

        RETURN ''Create table STAGING.ST_FLX_DIARIO_GENERO'';

    END;
';

EXECUTE IMMEDIATE '
    BEGIN

		CREATE OR REPLACE TABLE STAGING.ST_FLX_DIARIO_MES(
		MES VARCHAR2(10) NOT NULL,
		ETIQUETADELMES VARCHAR2(20) NOT NULL,
		ORIGEN VARCHAR2(15) NOT NULL,
		ZONAOBSERVACION VARCHAR2(100) NOT NULL,
		CATEGORIADELVISITANTE VARCHAR2(30) NOT NULL,
		VOLUMEN NUMBER NOT NULL,
		FILE_NAME VARCHAR2(200) NOT NULL,
		LOAD_DATE DATE NOT NULL
		)
		;

        RETURN ''Create table STAGING.ST_FLX_DIARIO_MES'';

    END;
';

EXECUTE IMMEDIATE '
    BEGIN

		CREATE OR REPLACE TABLE STAGING.ST_FLX_DIARIO_MES_EDAD(
		FECHA DATE NOT NULL,
		DIADELASEMANA VARCHAR2(10) NOT NULL,
		ORIGEN VARCHAR2(15) NOT NULL,
		EDAD VARCHAR2(10) NOT NULL,
		ZONAOBSERVACION VARCHAR2(100) NOT NULL,
		CATEGORIADELVISITANTE VARCHAR2(30) NOT NULL,
		VOLUMEN NUMBER NOT NULL,
		FILE_NAME VARCHAR2(200) NOT NULL,
		LOAD_DATE DATE NOT NULL
		)
		;

        RETURN ''Create table STAGING.ST_FLX_DIARIO_MES_EDAD'';

    END;
';

EXECUTE IMMEDIATE '
    BEGIN

		CREATE OR REPLACE TABLE STAGING.ST_FLX_DIARIO_MES_GENERO(
		FECHA DATE NOT NULL,
		DIADELASEMANA VARCHAR2(10) NOT NULL,
		ORIGEN VARCHAR2(15) NOT NULL,
		GENERO VARCHAR2(10) NOT NULL,
		ZONAOBSERVACION VARCHAR2(100) NOT NULL,
		CATEGORIADELVISITANTE VARCHAR2(30) NOT NULL,
		VOLUMEN NUMBER NOT NULL,
		FILE_NAME VARCHAR2(200) NOT NULL,
		LOAD_DATE DATE NOT NULL
		)
		;

        RETURN ''Create table STAGING.ST_FLX_DIARIO_MES_GENERO'';

    END;
';

EXECUTE IMMEDIATE '
    BEGIN

		CREATE OR REPLACE TABLE STAGING.ST_FLX_DIARIO_MES_MUNICIPIO(
		FECHA DATE NOT NULL,
		DIADELASEMANA VARCHAR2(10) NOT NULL,
		ORIGEN VARCHAR2(15) NOT NULL,
		NOMBREMUNICIPIO VARCHAR2(200) NOT NULL,
		NOMBREPROVINCIA VARCHAR2(50) NOT NULL,
		ZONAOBSERVACION VARCHAR2(100) NOT NULL,
		CATEGORIADELVISITANTE VARCHAR2(30) NOT NULL,
		VOLUMEN NUMBER NOT NULL,
		FILE_NAME VARCHAR2(200) NOT NULL,
		LOAD_DATE DATE NOT NULL
		)
		;

        RETURN ''Create table STAGING.ST_FLX_DIARIO_MES_MUNICIPIO'';

    END;
';

EXECUTE IMMEDIATE '
    BEGIN

		CREATE OR REPLACE TABLE STAGING.ST_FLX_DIARIO_MES_NACIONALIDAD(
		FECHA DATE NOT NULL,
		DIADELASEMANA VARCHAR2(10) NOT NULL,
		ORIGEN VARCHAR2(15) NOT NULL,
		PAIS VARCHAR2(30) NOT NULL,
		ZONAOBSERVACION VARCHAR2(100) NOT NULL,
		CATEGORIADELVISITANTE VARCHAR2(30) NOT NULL,
		VOLUMEN NUMBER NOT NULL,
		FILE_NAME VARCHAR2(200) NOT NULL,
		LOAD_DATE DATE NOT NULL
		)
		;

        RETURN ''Create table STAGING.ST_FLX_DIARIO_MES_NACIONALIDAD'';

    END;
';

EXECUTE IMMEDIATE '
    BEGIN

		CREATE OR REPLACE TABLE STAGING.ST_FLX_DIARIO_MUNICIPIO(
		FECHA DATE NOT NULL,
		DIADELASEMANA VARCHAR2(10) NOT NULL,
		ORIGEN VARCHAR2(15) NOT NULL,
		NOMBREMUNICIPIO VARCHAR2(200) NOT NULL,
		NOMBREPROVINCIA VARCHAR2(50) NOT NULL,
		ZONAOBSERVACION VARCHAR2(100) NOT NULL,
		CATEGORIADELVISITANTE VARCHAR2(30) NOT NULL,
		VOLUMEN NUMBER NOT NULL,
		FILE_NAME VARCHAR2(200) NOT NULL,
		LOAD_DATE DATE NOT NULL
		)
		;

        RETURN ''Create table STAGING.ST_FLX_DIARIO_MUNICIPIO'';

    END;
';

EXECUTE IMMEDIATE '
    BEGIN

		CREATE OR REPLACE TABLE STAGING.ST_FLX_DIARIO_NACIONALIDAD(
		FECHA DATE NOT NULL,
		DIADELASEMANA VARCHAR2(10) NOT NULL,
		ORIGEN VARCHAR2(15) NOT NULL,
		PAIS VARCHAR2(30) NOT NULL,
		ZONAOBSERVACION VARCHAR2(100) NOT NULL,
		CATEGORIADELVISITANTE VARCHAR2(30) NOT NULL,
		VOLUMEN NUMBER NOT NULL,
		FILE_NAME VARCHAR2(200) NOT NULL,
		LOAD_DATE DATE NOT NULL
		)
		;

        RETURN ''Create table STAGING.ST_FLX_DIARIO_NACIONALIDAD'';

    END;
';

EXECUTE IMMEDIATE '
    BEGIN

		CREATE OR REPLACE TABLE STAGING.ST_FLX_DURACIONESTANCIA(
		FECHA DATE NOT NULL,
		DIADELASEMANA VARCHAR2(10) NOT NULL,
		ORIGEN VARCHAR2(15) NOT NULL,
		ZONAOBSERVACION VARCHAR2(100) NOT NULL,
		CATEGORIADELVISITANTE VARCHAR2(30) NOT NULL,
		DURACIONDELAESTANCIA VARCHAR2(30) NOT NULL,
		VOLUMEN NUMBER NOT NULL,
		FILE_NAME VARCHAR2(200) NOT NULL,
		LOAD_DATE DATE NOT NULL
		)
		;

        RETURN ''Create table STAGING.ST_FLX_DURACIONESTANCIA'';

    END;
';

EXECUTE IMMEDIATE '
    BEGIN

		CREATE OR REPLACE TABLE STAGING.ST_FLX_DURACIONESTANCIA_MUNICIPIO(
		FECHA DATE NOT NULL,
		DIADELASEMANA VARCHAR2(10) NOT NULL,
		ORIGEN VARCHAR2(15) NOT NULL,
		NOMBREMUNICIPIO VARCHAR2(200) NOT NULL,
		NOMBREPROVINCIA VARCHAR2(50) NOT NULL,
		ZONAOBSERVACION VARCHAR2(100) NOT NULL,
		CATEGORIADELVISITANTE VARCHAR2(30) NOT NULL,
		DURACIONDELAESTANCIA VARCHAR2(30) NOT NULL,
		VOLUMEN NUMBER NOT NULL,
		FILE_NAME VARCHAR2(200) NOT NULL,
		LOAD_DATE DATE NOT NULL
		)
		;

        RETURN ''Create table STAGING.ST_FLX_DURACIONESTANCIA_MUNICIPIO'';

    END;
';

EXECUTE IMMEDIATE '
    BEGIN

		CREATE OR REPLACE TABLE STAGING.ST_FLX_DURACIONESTANCIA_NACIONALIDAD(
		FECHA DATE NOT NULL,
		DIADELASEMANA VARCHAR2(10) NOT NULL,
		ORIGEN VARCHAR2(15) NOT NULL,
		PAIS VARCHAR2(30) NOT NULL,
		ZONAOBSERVACION VARCHAR2(100) NOT NULL,
		CATEGORIADELVISITANTE VARCHAR2(30) NOT NULL,
		DURACIONDELAESTANCIA VARCHAR2(30) NOT NULL,
		VOLUMEN NUMBER NOT NULL,
		FILE_NAME VARCHAR2(200) NOT NULL,
		LOAD_DATE DATE NOT NULL
		)
		;

        RETURN ''Create table STAGING.ST_FLX_DURACIONESTANCIA_NACIONALIDAD'';

    END;
';

EXECUTE IMMEDIATE '
    BEGIN

		CREATE OR REPLACE TABLE STAGING.ST_FLX_LLEGADA(
		FECHA DATE NOT NULL,
		DIADELASEMANA VARCHAR2(10) NOT NULL,
		ORIGEN VARCHAR2(15) NOT NULL,
		ZONAOBSERVACION VARCHAR2(100) NOT NULL,
		CATEGORIADELVISITANTE VARCHAR2(30) NOT NULL,
		VOLUMEN NUMBER NOT NULL,
		FILE_NAME VARCHAR2(200) NOT NULL,
		LOAD_DATE DATE NOT NULL
		)
		;

        RETURN ''Create table STAGING.ST_FLX_LLEGADA'';

    END;
';

EXECUTE IMMEDIATE '
    BEGIN

		CREATE OR REPLACE TABLE STAGING.ST_FLX_LLEGADA_EDAD(
		FECHA DATE NOT NULL,
		DIADELASEMANA VARCHAR2(10) NOT NULL,
		ORIGEN VARCHAR2(15) NOT NULL,
		EDAD VARCHAR2(10) NOT NULL,
		ZONAOBSERVACION VARCHAR2(100) NOT NULL,
		CATEGORIADELVISITANTE VARCHAR2(30) NOT NULL,
		VOLUMEN NUMBER NOT NULL,
		FILE_NAME VARCHAR2(200) NOT NULL,
		LOAD_DATE DATE NOT NULL
		)
		;

        RETURN ''Create table STAGING.ST_FLX_LLEGADA_EDAD'';

    END;
';

EXECUTE IMMEDIATE '
    BEGIN

		CREATE OR REPLACE TABLE STAGING.ST_FLX_LLEGADA_GENERO(
		FECHA DATE NOT NULL,
		DIADELASEMANA VARCHAR2(10) NOT NULL,
		ORIGEN VARCHAR2(15) NOT NULL,
		GENERO VARCHAR2(10) NOT NULL,
		ZONAOBSERVACION VARCHAR2(100) NOT NULL,
		CATEGORIADELVISITANTE VARCHAR2(30) NOT NULL,
		VOLUMEN NUMBER NOT NULL,
		FILE_NAME VARCHAR2(200) NOT NULL,
		LOAD_DATE DATE NOT NULL
		)
		;

        RETURN ''Create table STAGING.ST_FLX_LLEGADA_GENERO'';

    END;
';

EXECUTE IMMEDIATE '
    BEGIN

		CREATE OR REPLACE TABLE STAGING.ST_FLX_LLEGADA_MUNICIPIO(
		FECHA DATE NOT NULL,
		DIADELASEMANA VARCHAR2(10) NOT NULL,
		ORIGEN VARCHAR2(15) NOT NULL,
		NOMBREMUNICIPIO VARCHAR2(200) NOT NULL,
		NOMBREPROVINCIA VARCHAR2(50) NOT NULL,
		ZONAOBSERVACION VARCHAR2(100) NOT NULL,
		CATEGORIADELVISITANTE VARCHAR2(30) NOT NULL,
		VOLUMEN NUMBER NOT NULL,
		FILE_NAME VARCHAR2(200) NOT NULL,
		LOAD_DATE DATE NOT NULL
		)
		;

        RETURN ''Create table STAGING.ST_FLX_LLEGADA_MUNICIPIO'';

    END;
';

EXECUTE IMMEDIATE '
    BEGIN

		CREATE OR REPLACE TABLE STAGING.ST_FLX_LLEGADA_NACIONALIDAD(
		FECHA DATE NOT NULL,
		DIADELASEMANA VARCHAR2(10) NOT NULL,
		ORIGEN VARCHAR2(15) NOT NULL,
		PAIS VARCHAR2(30) NOT NULL,
		ZONAOBSERVACION VARCHAR2(100) NOT NULL,
		CATEGORIADELVISITANTE VARCHAR2(30) NOT NULL,
		VOLUMEN NUMBER NOT NULL,
		FILE_NAME VARCHAR2(200) NOT NULL,
		LOAD_DATE DATE NOT NULL
		)
		;

        RETURN ''Create table STAGING.ST_FLX_LLEGADA_NACIONALIDAD'';

    END;
';

EXECUTE IMMEDIATE '
    BEGIN

		CREATE OR REPLACE TABLE STAGING.ST_FLX_LUGARACTIVIDAD_DIAVISITA(
		FECHA DATE NOT NULL,
		DIADELASEMANA VARCHAR2(10) NOT NULL,
		ORIGEN VARCHAR2(15) NOT NULL,
		MUNICIPIOZONADIARIADIAVISITA VARCHAR2(200) NOT NULL,
		PROVINCIAZONADIARIADIAVISITA VARCHAR2(50) NOT NULL,
		ZONAOBSERVACION VARCHAR2(100) NOT NULL,
		CATEGORIADELVISITANTE VARCHAR2(30) NOT NULL,
		VOLUMEN NUMBER NOT NULL,
		FILE_NAME VARCHAR2(200) NOT NULL,
		LOAD_DATE DATE NOT NULL
		)
		;

        RETURN ''Create table STAGING.ST_FLX_LUGARACTIVIDAD_DIAVISITA'';

    END;
';

EXECUTE IMMEDIATE '
    BEGIN

		CREATE OR REPLACE TABLE STAGING.ST_FLX_LUGARACTIVIDAD_DIAVISITA_MUNICIPIO(
		FECHA DATE NOT NULL,
		DIADELASEMANA VARCHAR2(10) NOT NULL,
		ORIGEN VARCHAR2(15) NOT NULL,
		NOMBREMUNICIPIO VARCHAR2(200) NOT NULL,
		NOMBREPROVINCIA VARCHAR2(50) NOT NULL,
		MUNICIPIOZONADIARIADIAVISITA VARCHAR2(200) NOT NULL,
		PROVINCIAZONADIARIADIAVISITA VARCHAR2(50) NOT NULL,
		ZONAOBSERVACION VARCHAR2(100) NOT NULL,
		CATEGORIADELVISITANTE VARCHAR2(30) NOT NULL,
		VOLUMEN NUMBER NOT NULL,
		FILE_NAME VARCHAR2(200) NOT NULL,
		LOAD_DATE DATE NOT NULL
		)
		;

        RETURN ''Create table STAGING.ST_FLX_LUGARACTIVIDAD_DIAVISITA_MUNICIPIO'';

    END;
';

EXECUTE IMMEDIATE '
    BEGIN

		CREATE OR REPLACE TABLE STAGING.ST_FLX_LUGARACTIVIDAD_DIAVISITA_MUNICIPIO_SEMANA(
		SEMANA DATE NOT NULL,
		ORIGEN VARCHAR2(15) NOT NULL,
		NOMBREMUNICIPIO VARCHAR2(200) NOT NULL,
		NOMBREPROVINCIA VARCHAR2(50) NOT NULL,
		MUNICIPIOZONADIARIADIAVISITA VARCHAR2(200) NOT NULL,
		PROVINCIAZONADIARIADIAVISITA VARCHAR2(50) NOT NULL,
		ZONAOBSERVACION VARCHAR2(100) NOT NULL,
		CATEGORIADELVISITANTE VARCHAR2(30) NOT NULL,
		VOLUMEN NUMBER NOT NULL,
		FILE_NAME VARCHAR2(200) NOT NULL,
		LOAD_DATE DATE NOT NULL
		)
		;

        RETURN ''Create table STAGING.ST_FLX_LUGARACTIVIDAD_DIAVISITA_MUNICIPIO_SEMANA'';

    END;
';

EXECUTE IMMEDIATE '
    BEGIN

		CREATE OR REPLACE TABLE STAGING.ST_FLX_LUGARACTIVIDAD_DIAVISITA_NACIONALIDAD(
		FECHA DATE NOT NULL,
		DIADELASEMANA VARCHAR2(10) NOT NULL,
		ORIGEN VARCHAR2(15) NOT NULL,
		PAIS VARCHAR2(30) NOT NULL,
		MUNICIPIOZONADIARIADIAVISITA VARCHAR2(200) NOT NULL,
		PROVINCIAZONADIARIADIAVISITA VARCHAR2(50) NOT NULL,
		ZONAOBSERVACION VARCHAR2(100) NOT NULL,
		CATEGORIADELVISITANTE VARCHAR2(30) NOT NULL,
		VOLUMEN NUMBER NOT NULL,
		FILE_NAME VARCHAR2(200) NOT NULL,
		LOAD_DATE DATE NOT NULL
		)
		;

        RETURN ''Create table STAGING.ST_FLX_LUGARACTIVIDAD_DIAVISITA_MUNICIPIO_SEMANA'';

    END;
';

EXECUTE IMMEDIATE '
    BEGIN

		CREATE OR REPLACE TABLE STAGING.ST_FLX_LUGARACTIVIDAD_DIAVISITA_NACIONALIDAD_SEMANA(
		SEMANA DATE NOT NULL,
		ORIGEN VARCHAR2(15) NOT NULL,
		PAIS VARCHAR2(30) NOT NULL,
		MUNICIPIOZONADIARIADIAVISITA VARCHAR2(200) NOT NULL,
		PROVINCIAZONADIARIADIAVISITA VARCHAR2(50) NOT NULL,
		ZONAOBSERVACION VARCHAR2(100) NOT NULL,
		CATEGORIADELVISITANTE VARCHAR2(30) NOT NULL,
		VOLUMEN NUMBER NOT NULL,
		FILE_NAME VARCHAR2(200) NOT NULL,
		LOAD_DATE DATE NOT NULL
		)
		;

        RETURN ''Create table STAGING.ST_FLX_LUGARACTIVIDAD_DIAVISITA_MUNICIPIO_SEMANA'';

    END;
';

EXECUTE IMMEDIATE '
    BEGIN

		CREATE OR REPLACE TABLE STAGING.ST_FLX_LUGARACTIVIDAD_DIAVISITA_SEMANA(
		SEMANA DATE NOT NULL,
		ORIGEN VARCHAR2(15) NOT NULL,
		MUNICIPIOZONADIARIADIAVISITA VARCHAR2(200) NOT NULL,
		PROVINCIAZONADIARIADIAVISITA VARCHAR2(50) NOT NULL,
		ZONAOBSERVACION VARCHAR2(100) NOT NULL,
		CATEGORIADELVISITANTE VARCHAR2(30) NOT NULL,
		VOLUMEN NUMBER NOT NULL,
		FILE_NAME VARCHAR2(200) NOT NULL,
		LOAD_DATE DATE NOT NULL
		)
		;

        RETURN ''Create table STAGING.ST_FLX_LUGARACTIVIDAD_DIAVISITA_SEMANA'';

    END;
';

EXECUTE IMMEDIATE '
    BEGIN

		CREATE OR REPLACE TABLE STAGING.ST_FLX_LUGARACTIVIDAD_VISPERA(
		FECHA DATE NOT NULL,
		DIADELASEMANA VARCHAR2(10) NOT NULL,
		ORIGEN VARCHAR2(15) NOT NULL,
		MUNICIPIOZONADIARIAVISPERA VARCHAR2(200) NOT NULL,
		PROVINCIAZONADIARIAVISPERA VARCHAR2(50) NOT NULL,
		ZONAOBSERVACION VARCHAR2(100) NOT NULL,
		CATEGORIADELVISITANTE VARCHAR2(30) NOT NULL,
		VOLUMEN NUMBER NOT NULL,
		FILE_NAME VARCHAR2(200) NOT NULL,
		LOAD_DATE DATE NOT NULL
		)
		;

        RETURN ''Create table STAGING.ST_FLX_LUGARACTIVIDAD_VISPERA'';

    END;
';

EXECUTE IMMEDIATE '
    BEGIN

		CREATE OR REPLACE TABLE STAGING.ST_FLX_LUGARACTIVIDAD_VISPERA_MUNICIPIO(
		FECHA DATE NOT NULL,
		DIADELASEMANA VARCHAR2(10) NOT NULL,
		ORIGEN VARCHAR2(15) NOT NULL,
		NOMBREMUNICIPIO VARCHAR2(200) NOT NULL,
		NOMBREPROVINCIA VARCHAR2(50) NOT NULL,
		MUNICIPIOZONADIARIAVISPERA VARCHAR2(200) NOT NULL,
		PROVINCIAZONADIARIAVISPERA VARCHAR2(50) NOT NULL,
		ZONAOBSERVACION VARCHAR2(100) NOT NULL,
		CATEGORIADELVISITANTE VARCHAR2(30) NOT NULL,
		VOLUMEN NUMBER NOT NULL,
		FILE_NAME VARCHAR2(200) NOT NULL,
		LOAD_DATE DATE NOT NULL
		)
		;

        RETURN ''Create table STAGING.ST_FLX_LUGARACTIVIDAD_VISPERA_MUNICIPIO'';

    END;
';

EXECUTE IMMEDIATE '
    BEGIN

		CREATE OR REPLACE TABLE STAGING.ST_FLX_LUGARACTIVIDAD_VISPERA_MUNICIPIO_SEMANA(
		SEMANA DATE NOT NULL,
		ORIGEN VARCHAR2(15) NOT NULL,
		NOMBREMUNICIPIO VARCHAR2(200) NOT NULL,
		NOMBREPROVINCIA VARCHAR2(50) NOT NULL,
		ZONAOBSERVACION VARCHAR2(100) NOT NULL,
		CATEGORIADELVISITANTE VARCHAR2(30) NOT NULL,
		MUNICIPIOZONADIARIAVISPERA VARCHAR2(200) NOT NULL,
		PROVINCIAZONADIARIAVISPERA VARCHAR2(50) NOT NULL,
		VOLUMEN NUMBER NOT NULL,
		FILE_NAME VARCHAR2(200) NOT NULL,
		LOAD_DATE DATE NOT NULL
		)
		;


        RETURN ''Create table STAGING.ST_FLX_LUGARACTIVIDAD_VISPERA_MUNICIPIO_SEMANA'';

    END;
';

EXECUTE IMMEDIATE '
    BEGIN

		CREATE OR REPLACE TABLE STAGING.ST_FLX_LUGARACTIVIDAD_VISPERA_NACIONALIDAD(
		FECHA DATE NOT NULL,
		DIADELASEMANA VARCHAR2(10) NOT NULL,
		ORIGEN VARCHAR2(15) NOT NULL,
		PAIS VARCHAR2(30) NOT NULL,
		MUNICIPIOZONADIARIAVISPERA VARCHAR2(200) NOT NULL,
		PROVINCIAZONADIARIAVISPERA VARCHAR2(50) NOT NULL,
		ZONAOBSERVACION VARCHAR2(100) NOT NULL,
		CATEGORIADELVISITANTE VARCHAR2(30) NOT NULL,
		VOLUMEN NUMBER NOT NULL,
		FILE_NAME VARCHAR2(200) NOT NULL,
		LOAD_DATE DATE NOT NULL
		)
		;

        RETURN ''Create table STAGING.ST_FLX_LUGARACTIVIDAD_VISPERA_NACIONALIDAD'';

    END;
';

EXECUTE IMMEDIATE '
    BEGIN

		CREATE OR REPLACE TABLE STAGING.ST_FLX_LUGARACTIVIDAD_VISPERA_NACIONALIDAD_SEMANA(
		SEMANA DATE NOT NULL,
		ORIGEN VARCHAR2(15) NOT NULL,
		PAIS VARCHAR2(30) NOT NULL,
		ZONAOBSERVACION VARCHAR2(100) NOT NULL,
		CATEGORIADELVISITANTE VARCHAR2(30) NOT NULL,
		MUNICIPIOZONADIARIAVISPERA VARCHAR2(200) NOT NULL,
		PROVINCIAZONADIARIAVISPERA VARCHAR2(50) NOT NULL,
		VOLUMEN NUMBER NOT NULL,
		FILE_NAME VARCHAR2(200) NOT NULL,
		LOAD_DATE DATE NOT NULL
		)
		;

        RETURN ''Create table STAGING.ST_FLX_LUGARACTIVIDAD_VISPERA_NACIONALIDAD_SEMANA'';

    END;
';

EXECUTE IMMEDIATE '
    BEGIN

		CREATE OR REPLACE TABLE STAGING.ST_FLX_LUGARACTIVIDAD_VISPERA_SEMANA(
		SEMANA DATE NOT NULL,
		ORIGEN VARCHAR2(15) NOT NULL,
		MUNICIPIOZONADIARIAVISPERA VARCHAR2(200) NOT NULL,
		PROVINCIAZONADIARIAVISPERA VARCHAR2(50) NOT NULL,
		ZONAOBSERVACION VARCHAR2(100) NOT NULL,
		CATEGORIADELVISITANTE VARCHAR2(30) NOT NULL,
		VOLUMEN NUMBER NOT NULL,
		FILE_NAME VARCHAR2(200) NOT NULL,
		LOAD_DATE DATE NOT NULL
		)
		;

        RETURN ''Create table STAGING.ST_FLX_LUGARACTIVIDAD_VISPERA_SEMANA'';

    END;
';

EXECUTE IMMEDIATE '
    BEGIN

		CREATE OR REPLACE TABLE STAGING.ST_FLX_LUGARNOCHE_DIAVISITA(
		FECHA DATE NOT NULL,
		DIADELASEMANA VARCHAR2(10) NOT NULL,
		ORIGEN VARCHAR2(15) NOT NULL,
		MUNICIPIOZONAPERNOCTACIONDIAVISITA VARCHAR2(200) NOT NULL,
		PROVINCIAZONAPERNOCTACIONDIAVISITA VARCHAR2(50) NOT NULL,
		ZONAOBSERVACION VARCHAR2(100) NOT NULL,
		CATEGORIADELVISITANTE VARCHAR2(30) NOT NULL,
		VOLUMEN NUMBER NOT NULL,
		FILE_NAME VARCHAR2(200) NOT NULL,
		LOAD_DATE DATE NOT NULL
		)
		;

        RETURN ''Create table STAGING.ST_FLX_LUGARNOCHE_DIAVISITA'';

    END;
';

EXECUTE IMMEDIATE '
    BEGIN

		CREATE OR REPLACE TABLE STAGING.ST_FLX_LUGARNOCHE_DIAVISITA_MUNICIPIO(
		FECHA DATE NOT NULL,
		DIADELASEMANA VARCHAR2(10) NOT NULL,
		ORIGEN VARCHAR2(15) NOT NULL,
		NOMBREMUNICIPIO VARCHAR2(200) NOT NULL,
		NOMBREPROVINCIA VARCHAR2(50) NOT NULL,
		MUNICIPIOZONAPERNOCTACIONDIAVISITA VARCHAR2(200) NOT NULL,
		PROVINCIAZONAPERNOCTACIONDIAVISITA VARCHAR2(50) NOT NULL,
		ZONAOBSERVACION VARCHAR2(100) NOT NULL,
		CATEGORIADELVISITANTE VARCHAR2(30) NOT NULL,
		VOLUMEN NUMBER NOT NULL,
		FILE_NAME VARCHAR2(200) NOT NULL,
		LOAD_DATE DATE NOT NULL
		)
		;

        RETURN ''Create table STAGING.ST_FLX_LUGARNOCHE_DIAVISITA_MUNICIPIO'';

    END;
';

EXECUTE IMMEDIATE '
    BEGIN

		CREATE OR REPLACE TABLE STAGING.ST_FLX_LUGARNOCHE_DIAVISITA_MUNICIPIO_SEMANA(
		SEMANA DATE NOT NULL,
		ORIGEN VARCHAR2(15) NOT NULL,
		NOMBREMUNICIPIO VARCHAR2(200) NOT NULL,
		NOMBREPROVINCIA VARCHAR2(50) NOT NULL,
		MUNICIPIOZONAPERNOCTACIONDIAVISITA VARCHAR2(200) NOT NULL,
		PROVINCIAZONAPERNOCTACIONDIAVISITA VARCHAR2(50) NOT NULL,
		ZONAOBSERVACION VARCHAR2(100) NOT NULL,
		CATEGORIADELVISITANTE VARCHAR2(30) NOT NULL,
		VOLUMEN NUMBER NOT NULL,
		FILE_NAME VARCHAR2(200) NOT NULL,
		LOAD_DATE DATE NOT NULL
		)
		;
        
        RETURN ''Create table STAGING.ST_FLX_LUGARNOCHE_DIAVISITA_MUNICIPIO_SEMANA'';

    END;
';

EXECUTE IMMEDIATE '
    BEGIN

		CREATE OR REPLACE TABLE STAGING.ST_FLX_LUGARNOCHE_DIAVISITA_NACIONALIDAD(
		FECHA DATE NOT NULL,
		DIADELASEMANA VARCHAR2(10) NOT NULL,
		ORIGEN VARCHAR2(15) NOT NULL,
		PAIS VARCHAR2(30) NOT NULL,
		MUNICIPIOZONAPERNOCTACIONDIAVISITA VARCHAR2(200) NOT NULL,
		PROVINCIAZONAPERNOCTACIONDIAVISITA VARCHAR2(50) NOT NULL,
		ZONAOBSERVACION VARCHAR2(100) NOT NULL,
		CATEGORIADELVISITANTE VARCHAR2(30) NOT NULL,
		VOLUMEN NUMBER NOT NULL,
		FILE_NAME VARCHAR2(200) NOT NULL,
		LOAD_DATE DATE NOT NULL
		)
		;

        RETURN ''Create table STAGING.ST_FLX_LUGARNOCHE_DIAVISITA_NACIONALIDAD'';

    END;
';

EXECUTE IMMEDIATE '
    BEGIN

		CREATE OR REPLACE TABLE STAGING.ST_FLX_LUGARNOCHE_DIAVISITA_NACIONALIDAD_SEMANA(
		SEMANA DATE NOT NULL,
		ORIGEN VARCHAR2(15) NOT NULL,
		PAIS VARCHAR2(30) NOT NULL,
		MUNICIPIOZONAPERNOCTACIONDIAVISITA VARCHAR2(200) NOT NULL,
		PROVINCIAZONAPERNOCTACIONDIAVISITA VARCHAR2(50) NOT NULL,
		ZONAOBSERVACION VARCHAR2(100) NOT NULL,
		CATEGORIADELVISITANTE VARCHAR2(30) NOT NULL,
		VOLUMEN NUMBER NOT NULL,
		FILE_NAME VARCHAR2(200) NOT NULL,
		LOAD_DATE DATE NOT NULL
		)
		;

        RETURN ''Create table STAGING.ST_FLX_LUGARNOCHE_DIAVISITA_NACIONALIDAD_SEMANA'';

    END;
';

EXECUTE IMMEDIATE '
    BEGIN

		CREATE OR REPLACE TABLE STAGING.ST_FLX_LUGARNOCHE_DIAVISITA_SEMANA(
		SEMANA DATE NOT NULL,
		ORIGEN VARCHAR2(15) NOT NULL,
		MUNICIPIOZONAPERNOCTACIONDIAVISITA VARCHAR2(200) NOT NULL,
		PROVINCIAZONAPERNOCTACIONDIAVISITA VARCHAR2(50) NOT NULL,
		ZONAOBSERVACION VARCHAR2(100) NOT NULL,
		CATEGORIADELVISITANTE VARCHAR2(30) NOT NULL,
		VOLUMEN NUMBER NOT NULL,
		FILE_NAME VARCHAR2(200) NOT NULL,
		LOAD_DATE DATE NOT NULL
		)
		;

        RETURN ''Create table STAGING.ST_FLX_LUGARNOCHE_DIAVISITA_SEMANA'';

    END;
';

EXECUTE IMMEDIATE '
    BEGIN

		CREATE OR REPLACE TABLE STAGING.ST_FLX_LUGARNOCHE_VISPERA(
		FECHA DATE NOT NULL,
		DIADELASEMANA VARCHAR2(10) NOT NULL,
		ORIGEN VARCHAR2(15) NOT NULL,
		MUNICIPIOZONAPERNOCTACIONVISPERA VARCHAR2(200) NOT NULL,
		PROVINCIAZONAPERNOCTACIONVISPERA VARCHAR2(50) NOT NULL,
		ZONAOBSERVACION VARCHAR2(100) NOT NULL,
		CATEGORIADELVISITANTE VARCHAR2(30) NOT NULL,
		VOLUMEN NUMBER NOT NULL,
		FILE_NAME VARCHAR2(200) NOT NULL,
		LOAD_DATE DATE NOT NULL
		)
		;

        RETURN ''Create table STAGING.ST_FLX_LUGARNOCHE_VISPERA'';

    END;
';


EXECUTE IMMEDIATE '
    BEGIN

		CREATE OR REPLACE TABLE STAGING.ST_FLX_LUGARNOCHE_VISPERA_MUNICIPIO(
		FECHA DATE NOT NULL,
		DIADELASEMANA VARCHAR2(10) NOT NULL,
		ORIGEN VARCHAR2(15) NOT NULL,
		NOMBREMUNICIPIO VARCHAR2(200) NOT NULL,
		NOMBREPROVINCIA VARCHAR2(50) NOT NULL,
		MUNICIPIOZONAPERNOCTACIONVISPERA VARCHAR2(200) NOT NULL,
		PROVINCIAZONAPERNOCTACIONVISPERA VARCHAR2(50) NOT NULL,
		ZONAOBSERVACION VARCHAR2(100) NOT NULL,
		CATEGORIADELVISITANTE VARCHAR2(30) NOT NULL,
		VOLUMEN NUMBER NOT NULL,
		FILE_NAME VARCHAR2(200) NOT NULL,
		LOAD_DATE DATE NOT NULL
		)
		;

        RETURN ''Create table STAGING.ST_FLX_LUGARNOCHE_VISPERA_MUNICIPIO'';

    END;
';

EXECUTE IMMEDIATE '
    BEGIN

		CREATE OR REPLACE TABLE STAGING.ST_FLX_LUGARNOCHE_VISPERA_MUNICIPIO_SEMANA(
		SEMANA DATE NOT NULL,
		ORIGEN VARCHAR2(15) NOT NULL,
		NOMBREMUNICIPIO VARCHAR2(200) NOT NULL,
		NOMBREPROVINCIA VARCHAR2(50) NOT NULL,
		MUNICIPIOZONAPERNOCTACIONVISPERA VARCHAR2(200) NOT NULL,
		PROVINCIAZONAPERNOCTACIONVISPERA VARCHAR2(50) NOT NULL,
		ZONAOBSERVACION VARCHAR2(100) NOT NULL,
		CATEGORIADELVISITANTE VARCHAR2(30) NOT NULL,
		VOLUMEN NUMBER NOT NULL,
		FILE_NAME VARCHAR2(200) NOT NULL,
		LOAD_DATE DATE NOT NULL
		)
		;

        RETURN ''Create table STAGING.ST_FLX_LUGARNOCHE_VISPERA_MUNICIPIO_SEMANA'';

    END;
';

EXECUTE IMMEDIATE '
    BEGIN

		CREATE OR REPLACE TABLE STAGING.ST_FLX_LUGARNOCHE_VISPERA_NACIONALIDAD(
		FECHA DATE NOT NULL,
		DIADELASEMANA VARCHAR2(10) NOT NULL,
		ORIGEN VARCHAR2(15) NOT NULL,
		PAIS VARCHAR2(30) NOT NULL,
		MUNICIPIOZONAPERNOCTACIONVISPERA VARCHAR2(200) NOT NULL,
		PROVINCIAZONAPERNOCTACIONVISPERA VARCHAR2(50) NOT NULL,
		ZONAOBSERVACION VARCHAR2(100) NOT NULL,
		CATEGORIADELVISITANTE VARCHAR2(30) NOT NULL,
		VOLUMEN NUMBER NOT NULL,
		FILE_NAME VARCHAR2(200) NOT NULL,
		LOAD_DATE DATE NOT NULL
		)
		;

        RETURN ''Create table STAGING.ST_FLX_LUGARNOCHE_VISPERA_NACIONALIDAD'';

    END;
';

EXECUTE IMMEDIATE '
    BEGIN

		CREATE OR REPLACE TABLE STAGING.ST_FLX_LUGARNOCHE_VISPERA_NACIONALIDAD_SEMANA(
		SEMANA DATE NOT NULL,
		ORIGEN VARCHAR2(15) NOT NULL,
		PAIS VARCHAR2(30) NOT NULL,
		MUNICIPIOZONAPERNOCTACIONVISPERA VARCHAR2(200) NOT NULL,
		PROVINCIAZONAPERNOCTACIONVISPERA VARCHAR2(50) NOT NULL,
		ZONAOBSERVACION VARCHAR2(100) NOT NULL,
		CATEGORIADELVISITANTE VARCHAR2(30) NOT NULL,
		VOLUMEN NUMBER NOT NULL,
		FILE_NAME VARCHAR2(200) NOT NULL,
		LOAD_DATE DATE NOT NULL
		)
		;

        RETURN ''Create table STAGING.ST_FLX_LUGARNOCHE_VISPERA_NACIONALIDAD_SEMANA'';

    END;
';

EXECUTE IMMEDIATE '
    BEGIN

		CREATE OR REPLACE TABLE STAGING.ST_FLX_LUGARNOCHE_VISPERA_SEMANA(
		SEMANA DATE NOT NULL,
		ORIGEN VARCHAR2(15) NOT NULL,
		MUNICIPIOZONAPERNOCTACIONVISPERA VARCHAR2(200) NOT NULL,
		PROVINCIAZONAPERNOCTACIONVISPERA VARCHAR2(50) NOT NULL,
		ZONAOBSERVACION VARCHAR2(100) NOT NULL,
		CATEGORIADELVISITANTE VARCHAR2(30) NOT NULL,
		VOLUMEN NUMBER NOT NULL,
		FILE_NAME VARCHAR2(200) NOT NULL,
		LOAD_DATE DATE NOT NULL
		)
		;

        RETURN ''Create table STAGING.ST_FLX_LUGARNOCHE_VISPERA_SEMANA'';

    END;
';

EXECUTE IMMEDIATE '
    BEGIN

		CREATE OR REPLACE TABLE STAGING.ST_FLX_NOCHEESTANCIA(
		FECHA DATE NOT NULL,
		DIADELASEMANA VARCHAR2(10) NOT NULL,
		ORIGEN VARCHAR2(15) NOT NULL,
		ZONAOBSERVACION VARCHAR2(100) NOT NULL,
		CATEGORIADELVISITANTE VARCHAR2(30) NOT NULL,
		DURACIONESTANCIA VARCHAR2(30) NOT NULL,
		DURACIONESTANCIANUM NUMBER NOT NULL,
		VOLUMEN NUMBER NOT NULL,
		FILE_NAME VARCHAR2(200) NOT NULL,
		LOAD_DATE DATE NOT NULL
		)
		;

        RETURN ''Create table STAGING.ST_FLX_NOCHEESTANCIA'';

    END;
';

EXECUTE IMMEDIATE '
    BEGIN

		CREATE OR REPLACE TABLE STAGING.ST_FLX_NOCHEESTANCIA_MUNICIPIO(
		FECHA DATE NOT NULL,
		DIADELASEMANA VARCHAR2(10) NOT NULL,
		ORIGEN VARCHAR2(15) NOT NULL,
		NOMBREMUNICIPIO VARCHAR2(200) NOT NULL,
		NOMBREPROVINCIA VARCHAR2(50) NOT NULL,
		ZONAOBSERVACION VARCHAR2(100) NOT NULL,
		CATEGORIADELVISITANTE VARCHAR2(30) NOT NULL,
		DURACIONESTANCIA VARCHAR2(30) NOT NULL,
		DURACIONESTANCIANUM NUMBER NOT NULL,
		VOLUMEN NUMBER NOT NULL,
		FILE_NAME VARCHAR2(200) NOT NULL,
		LOAD_DATE DATE NOT NULL
		)
		;

        RETURN ''Create table STAGING.ST_FLX_NOCHEESTANCIA_MUNICIPIO'';

    END;
';

EXECUTE IMMEDIATE '
    BEGIN

		CREATE OR REPLACE TABLE STAGING.ST_FLX_NOCHEESTANCIA_NACIONALIDAD(
		FECHA DATE NOT NULL,
		DIADELASEMANA VARCHAR2(10) NOT NULL,
		ORIGEN VARCHAR2(15) NOT NULL,
		PAIS VARCHAR2(30) NOT NULL,
		ZONAOBSERVACION VARCHAR2(100) NOT NULL,
		CATEGORIADELVISITANTE VARCHAR2(30) NOT NULL,
		DURACIONESTANCIA VARCHAR2(30) NOT NULL,
		DURACIONESTANCIANUM NUMBER NOT NULL,
		VOLUMEN NUMBER NOT NULL,
		FILE_NAME VARCHAR2(200) NOT NULL,
		LOAD_DATE DATE NOT NULL
		)
		;

        RETURN ''Create table STAGING.ST_FLX_NOCHEESTANCIA_NACIONALIDAD'';

    END;
';

EXECUTE IMMEDIATE '
    BEGIN

		CREATE OR REPLACE TABLE STAGING.ST_FLX_NOCTURNO(
		FECHA DATE NOT NULL,
		DIADELASEMANA VARCHAR2(10) NOT NULL,
		ORIGEN VARCHAR2(15) NOT NULL,
		ZONAOBSERVACION VARCHAR2(100) NOT NULL,
		MUNICIPIOZONAPERNOCTACIONVISPERA VARCHAR2(200) NOT NULL,
		PROVINCIAZONAPERNOCTACIONVISPERA VARCHAR2(50) NOT NULL,
		CATEGORIADELVISITANTE VARCHAR2(30) NOT NULL,
		VOLUMEN NUMBER NOT NULL,
		FILE_NAME VARCHAR2(200) NOT NULL,
		LOAD_DATE DATE NOT NULL
		)
		;

        RETURN ''Create table STAGING.ST_FLX_NOCTURNO'';

    END;
';

EXECUTE IMMEDIATE '
    BEGIN

		CREATE OR REPLACE TABLE STAGING.ST_FLX_NOCTURNO_EDAD(
		FECHA DATE NOT NULL,
		DIADELASEMANA VARCHAR2(10) NOT NULL,
		ORIGEN VARCHAR2(15) NOT NULL,
		EDAD VARCHAR2(10) NOT NULL,
		ZONAOBSERVACION VARCHAR2(100) NOT NULL,
		MUNICIPIOZONAPERNOCTACIONVISPERA VARCHAR2(200) NOT NULL,
		PROVINCIAZONAPERNOCTACIONVISPERA VARCHAR2(50) NOT NULL,
		CATEGORIADELVISITANTE VARCHAR2(30) NOT NULL,
		VOLUMEN NUMBER NOT NULL,
		FILE_NAME VARCHAR2(200) NOT NULL,
		LOAD_DATE DATE NOT NULL
		)
		;

        RETURN ''Create table STAGING.ST_FLX_NOCTURNO_EDAD'';

    END;
';

EXECUTE IMMEDIATE '
    BEGIN

		CREATE OR REPLACE TABLE STAGING.ST_FLX_NOCTURNO_GENERO(
		FECHA DATE NOT NULL,
		DIADELASEMANA VARCHAR2(10) NOT NULL,
		ORIGEN VARCHAR2(15) NOT NULL,
		GENERO VARCHAR2(10) NOT NULL,
		ZONAOBSERVACION VARCHAR2(100) NOT NULL,
		MUNICIPIOZONAPERNOCTACIONVISPERA VARCHAR2(200) NOT NULL,
		PROVINCIAZONAPERNOCTACIONVISPERA VARCHAR2(50) NOT NULL,
		CATEGORIADELVISITANTE VARCHAR2(30) NOT NULL,
		VOLUMEN NUMBER NOT NULL,
		FILE_NAME VARCHAR2(200) NOT NULL,
		LOAD_DATE DATE NOT NULL
		)
		;

        RETURN ''Create table STAGING.ST_FLX_NOCTURNO_GENERO'';

    END;
';

EXECUTE IMMEDIATE '
    BEGIN

		CREATE OR REPLACE TABLE STAGING.ST_FLX_NOCTURNO_MES(
		MES VARCHAR2(10) NOT NULL,
		ETIQUETADELMES VARCHAR2(20) NOT NULL,
		ORIGEN VARCHAR2(15) NOT NULL,
		ZONAOBSERVACION VARCHAR2(100) NOT NULL,
		CATEGORIADELVISITANTE VARCHAR2(30) NOT NULL,
		VOLUMEN NUMBER NOT NULL,
		FILE_NAME VARCHAR2(200) NOT NULL,
		LOAD_DATE DATE NOT NULL
		)
		;

        RETURN ''Create table STAGING.ST_FLX_NOCTURNO_MES'';

    END;
';

EXECUTE IMMEDIATE '
    BEGIN
		
		CREATE OR REPLACE TABLE STAGING.ST_FLX_NOCTURNO_MES_EDAD(
		MES VARCHAR2(10) NOT NULL,
		ETIQUETADELMES VARCHAR2(20) NOT NULL,
		ORIGEN VARCHAR2(15) NOT NULL,
		EDAD VARCHAR2(10) NOT NULL,
		ZONAOBSERVACION VARCHAR2(100) NOT NULL,
		CATEGORIADELVISITANTE VARCHAR2(30) NOT NULL,
		VOLUMEN NUMBER NOT NULL,
		FILE_NAME VARCHAR2(200) NOT NULL,
		LOAD_DATE DATE NOT NULL
		)
		;

        RETURN ''Create table STAGING.ST_FLX_NOCTURNO_MES'';

    END;
';

EXECUTE IMMEDIATE '
    BEGIN

		CREATE OR REPLACE TABLE STAGING.ST_FLX_NOCTURNO_MES_GENERO(
		MES VARCHAR2(10) NOT NULL,
		ETIQUETADELMES VARCHAR2(20) NOT NULL,
		ORIGEN VARCHAR2(15) NOT NULL,
		GENERO VARCHAR2(10) NOT NULL,
		ZONAOBSERVACION VARCHAR2(100) NOT NULL,
		CATEGORIADELVISITANTE VARCHAR2(30) NOT NULL,
		VOLUMEN NUMBER NOT NULL,
		FILE_NAME VARCHAR2(200) NOT NULL,
		LOAD_DATE DATE NOT NULL
		)
		;

        RETURN ''Create table STAGING.ST_FLX_NOCTURNO_MES_GENERO'';

    END;
';

EXECUTE IMMEDIATE '
    BEGIN

		CREATE OR REPLACE TABLE STAGING.ST_FLX_NOCTURNO_MES_MUNICIPIO(
		MES VARCHAR2(10) NOT NULL,
		ETIQUETADELMES VARCHAR2(20) NOT NULL,
		ORIGEN VARCHAR2(15) NOT NULL,
		NOMBREMUNICIPIO VARCHAR2(200) NOT NULL,
		NOMBREPROVINCIA VARCHAR2(50) NOT NULL,
		ZONAOBSERVACION VARCHAR2(100) NOT NULL,
		CATEGORIADELVISITANTE VARCHAR2(30) NOT NULL,
		VOLUMEN NUMBER NOT NULL,
		FILE_NAME VARCHAR2(200) NOT NULL,
		LOAD_DATE DATE NOT NULL
		)
		;

        RETURN ''Create table STAGING.ST_FLX_NOCTURNO_MES_MUNICIPIO'';

    END;
';

EXECUTE IMMEDIATE '
    BEGIN

		CREATE OR REPLACE TABLE STAGING.ST_FLX_NOCTURNO_MES_NACIONALIDAD(
		MES VARCHAR2(10) NOT NULL,
		ETIQUETADELMES VARCHAR2(20) NOT NULL,
		ORIGEN VARCHAR2(15) NOT NULL,
		PAIS VARCHAR2(30) NOT NULL,
		ZONAOBSERVACION VARCHAR2(100) NOT NULL,
		CATEGORIADELVISITANTE VARCHAR2(30) NOT NULL,
		VOLUMEN NUMBER NOT NULL,
		FILE_NAME VARCHAR2(200) NOT NULL,
		LOAD_DATE DATE NOT NULL
		)
		;

        RETURN ''Create table STAGING.ST_FLX_NOCTURNO_MES_NACIONALIDAD'';

    END;
';

EXECUTE IMMEDIATE '
    BEGIN

		CREATE OR REPLACE TABLE STAGING.ST_FLX_NOCTURNO_MUNICIPIO(
		FECHA DATE NOT NULL,
		DIADELASEMANA VARCHAR2(10) NOT NULL,
		ORIGEN VARCHAR2(15) NOT NULL,
		NOMBREMUNICIPIO VARCHAR2(200) NOT NULL,
		NOMBREPROVINCIA VARCHAR2(50) NOT NULL,
		MUNICIPIOZONAPERNOCTACIONVISPERA VARCHAR2(200) NOT NULL,
		PROVINCIAZONAPERNOCTACIONVISPERA VARCHAR2(50) NOT NULL,
		ZONAOBSERVACION VARCHAR2(100) NOT NULL,
		CATEGORIADELVISITANTE VARCHAR2(30) NOT NULL,
		VOLUMEN NUMBER NOT NULL,
		FILE_NAME VARCHAR2(200) NOT NULL,
		LOAD_DATE DATE NOT NULL
		)
		;

        RETURN ''Create table STAGING.ST_FLX_NOCTURNO_MUNICIPIO'';

    END;
';

EXECUTE IMMEDIATE '
    BEGIN

		CREATE OR REPLACE TABLE STAGING.ST_FLX_NOCTURNO_NACIONALIDAD(
		FECHA DATE NOT NULL,
		DIADELASEMANA VARCHAR2(10) NOT NULL,
		ORIGEN VARCHAR2(15) NOT NULL,
		PAIS VARCHAR2(30) NOT NULL,
		ZONAOBSERVACION VARCHAR2(100) NOT NULL,
		MUNICIPIOZONAPERNOCTACIONVISPERA VARCHAR2(200) NOT NULL,
		PROVINCIAZONAPERNOCTACIONVISPERA VARCHAR2(50) NOT NULL,
		CATEGORIADELVISITANTE VARCHAR2(30) NOT NULL,
		VOLUMEN NUMBER NOT NULL,
		FILE_NAME VARCHAR2(200) NOT NULL,
		LOAD_DATE DATE NOT NULL
		)
		;

        RETURN ''Create table STAGING.ST_FLX_NOCTURNO_NACIONALIDAD'';

    END;
';

EXECUTE IMMEDIATE '
    BEGIN

		CREATE OR REPLACE TABLE STAGING.ST_FLX_RECURRENCIA(
		FECHA DATE NOT NULL,
		DIADELASEMANA VARCHAR2(10) NOT NULL,
		ORIGEN VARCHAR2(15) NOT NULL,
		ZONAOBSERVACION VARCHAR2(100) NOT NULL,
		CATEGORIADELVISITANTE VARCHAR2(30) NOT NULL,
		RECURRENCIA NUMBER NOT NULL,
		VOLUMEN NUMBER NOT NULL,
		FILE_NAME VARCHAR2(200) NOT NULL,
		LOAD_DATE DATE NOT NULL
		)
		;

        RETURN ''Create table STAGING.ST_FLX_RECURRENCIA'';

    END;
';

EXECUTE IMMEDIATE '
    BEGIN

		CREATE OR REPLACE TABLE STAGING.ST_FLX_RECURRENCIA_MUNICIPIO(
		FECHA DATE NOT NULL,
		DIADELASEMANA VARCHAR2(10) NOT NULL,
		ORIGEN VARCHAR2(15) NOT NULL,
		NOMBREMUNICIPIO VARCHAR2(200) NOT NULL,
		NOMBREPROVINCIA VARCHAR2(50) NOT NULL,
		ZONAOBSERVACION VARCHAR2(100) NOT NULL,
		CATEGORIADELVISITANTE VARCHAR2(30) NOT NULL,
		RECURRENCIA NUMBER NOT NULL,
		VOLUMEN NUMBER NOT NULL,
		FILE_NAME VARCHAR2(200) NOT NULL,
		LOAD_DATE DATE NOT NULL
		)
		;

        RETURN ''Create table STAGING.ST_FLX_RECURRENCIA_MUNICIPIO'';

    END;
';

EXECUTE IMMEDIATE '
    BEGIN

		CREATE OR REPLACE TABLE STAGING.ST_FLX_RECURRENCIA_NACIONALIDAD(
		FECHA DATE NOT NULL,
		DIADELASEMANA VARCHAR2(10) NOT NULL,
		ORIGEN VARCHAR2(15) NOT NULL,
		PAIS VARCHAR2(30) NOT NULL,
		ZONAOBSERVACION VARCHAR2(100) NOT NULL,
		CATEGORIADELVISITANTE VARCHAR2(30) NOT NULL,
		RECURRENCIA NUMBER NOT NULL,
		VOLUMEN NUMBER NOT NULL,
		FILE_NAME VARCHAR2(200) NOT NULL,
		LOAD_DATE DATE NOT NULL
		)
		;

        RETURN ''Create table STAGING.ST_FLX_RECURRENCIA_NACIONALIDAD'';

    END;
';

EXECUTE IMMEDIATE '
    BEGIN

		CREATE OR REPLACE TABLE STAGING.ST_FLX_SALIDA(
		FECHA DATE NOT NULL,
		DIADELASEMANA VARCHAR2(10) NOT NULL,
		ORIGEN VARCHAR2(15) NOT NULL,
		ZONAOBSERVACION VARCHAR2(100) NOT NULL,
		CATEGORIADELVISITANTE VARCHAR2(30) NOT NULL,
		VOLUMEN NUMBER NOT NULL,
		FILE_NAME VARCHAR2(200) NOT NULL,
		LOAD_DATE DATE NOT NULL
		)
		;

        RETURN ''Create table STAGING.ST_FLX_SALIDA'';

    END;
';

EXECUTE IMMEDIATE '
    BEGIN

		CREATE OR REPLACE TABLE STAGING.ST_FLX_SALIDA_EDAD(
		FECHA DATE NOT NULL,
		DIADELASEMANA VARCHAR2(10) NOT NULL,
		ORIGEN VARCHAR2(15) NOT NULL,
		EDAD VARCHAR2(10) NOT NULL,
		ZONAOBSERVACION VARCHAR2(100) NOT NULL,
		CATEGORIADELVISITANTE VARCHAR2(30) NOT NULL,
		VOLUMEN NUMBER NOT NULL,
		FILE_NAME VARCHAR2(200) NOT NULL,
		LOAD_DATE DATE NOT NULL
		)
		;

        RETURN ''Create table STAGING.ST_FLX_SALIDA_EDAD'';

    END;
';

EXECUTE IMMEDIATE '
    BEGIN

		CREATE OR REPLACE TABLE STAGING.ST_FLX_SALIDA_GENERO(
		FECHA DATE NOT NULL,
		DIADELASEMANA VARCHAR2(10) NOT NULL,
		ORIGEN VARCHAR2(15) NOT NULL,
		GENERO VARCHAR2(10) NOT NULL,
		ZONAOBSERVACION VARCHAR2(100) NOT NULL,
		CATEGORIADELVISITANTE VARCHAR2(30) NOT NULL,
		VOLUMEN NUMBER NOT NULL,
		FILE_NAME VARCHAR2(200) NOT NULL,
		LOAD_DATE DATE NOT NULL
		)
		;

        RETURN ''Create table STAGING.ST_FLX_SALIDA_GENERO'';

    END;
';

EXECUTE IMMEDIATE '
    BEGIN

		CREATE OR REPLACE TABLE STAGING.ST_FLX_SALIDA_MUNICIPIO(
		FECHA DATE NOT NULL,
		DIADELASEMANA VARCHAR2(10) NOT NULL,
		ORIGEN VARCHAR2(15) NOT NULL,
		NOMBREMUNICIPIO VARCHAR2(200) NOT NULL,
		NOMBREPROVINCIA VARCHAR2(50) NOT NULL,
		ZONAOBSERVACION VARCHAR2(100) NOT NULL,
		CATEGORIADELVISITANTE VARCHAR2(30) NOT NULL,
		VOLUMEN NUMBER NOT NULL,
		FILE_NAME VARCHAR2(200) NOT NULL,
		LOAD_DATE DATE NOT NULL
		)
		;

        RETURN ''Create table STAGING.ST_FLX_SALIDA_MUNICIPIO'';

    END;
';

EXECUTE IMMEDIATE '
    BEGIN

		CREATE OR REPLACE TABLE STAGING.ST_FLX_SALIDA_NACIONALIDAD(
		FECHA DATE NOT NULL,
		DIADELASEMANA VARCHAR2(10) NOT NULL,
		ORIGEN VARCHAR2(15) NOT NULL,
		PAIS VARCHAR2(30) NOT NULL,
		ZONAOBSERVACION VARCHAR2(100) NOT NULL,
		CATEGORIADELVISITANTE VARCHAR2(30) NOT NULL,
		VOLUMEN NUMBER NOT NULL,
		FILE_NAME VARCHAR2(200) NOT NULL,
		LOAD_DATE DATE NOT NULL
		)
		;
        
        RETURN ''Create table STAGING.ST_FLX_SALIDA_MUNICIPIO'';

    END;
';

*/

EXECUTE IMMEDIATE '
    BEGIN

                CREATE OR REPLACE TABLE STAGING.ST_FLX_SALIDA_NACIONALIDAD(
                FECHA DATE NOT NULL,
                DIADELASEMANA VARCHAR2(10) NOT NULL,
                ORIGEN VARCHAR2(15) NOT NULL,
                PAIS VARCHAR2(30) NOT NULL,
                ZONAOBSERVACION VARCHAR2(100) NOT NULL,
                CATEGORIADELVISITANTE VARCHAR2(30) NOT NULL,
                VOLUMEN NUMBER NOT NULL,
                FILE_NAME VARCHAR2(200) NOT NULL,
                LOAD_DATE DATE NOT NULL
                )
                ;

        RETURN ''Create table STAGING.ST_FLX_SALIDA_NACIONAL'';

    END;
';

/*

EXECUTE IMMEDIATE '
    BEGIN

		create or replace task STAGING.LOAD_FLX_CONTINUO
			schedule=''USING CRON  0 11 * * * Europe/Madrid''
			USER_TASK_MANAGED_INITIAL_WAREHOUSE_SIZE=''XLARGE''
			as BEGIN
				COPY INTO STAGING.ST_FLX_DIARIO(Fecha,DiaDeLaSemana,Origen,ZonaObservacion,CategoriaDelVisitante,Volumen, file_name,continuo, load_date)  FROM (SELECT  $1,$2,$3,$4,$5,$6, METADATA$FILENAME,''c'',to_timestamp_ntz(current_timestamp)  from ''@s3_stage/flux/continuo/'' ) pattern=''.*Diario_202.*''  file_format = ''csv_format_flx''  on_error = ''continue'';
				COPY INTO STAGING.ST_FLX_DIARIO_EDAD(Fecha,DiaDeLaSemana,Origen,Edad,ZonaObservacion,CategoriaDelVisitante,Volumen, file_name,continuo, load_date)  FROM (SELECT  $1,$2,$3,$4,$5,$6,$7, METADATA$FILENAME,''c'',to_timestamp_ntz(current_timestamp)  from ''@s3_stage/flux/continuo/'' ) pattern=''.*Diario_Edad_202.*''  file_format = ''csv_format_flx''  on_error = ''continue'';
				COPY INTO STAGING.ST_FLX_DIARIO_GENERO(Fecha,DiaDeLaSemana,Origen,Genero,ZonaObservacion,CategoriaDelVisitante,Volumen, file_name,continuo, load_date)  FROM (SELECT  $1,$2,$3,$4,$5,$6,$7, METADATA$FILENAME,''c'',to_timestamp_ntz(current_timestamp)  from ''@s3_stage/flux/continuo/'' ) pattern=''.*Diario_Genero_202.*''  file_format = ''csv_format_flx''  on_error = ''continue'';
				COPY INTO STAGING.ST_FLX_DIARIO_MUNICIPIO(Fecha,DiaDeLaSemana,Origen,NombreMunicipio,NombreProvincia,ZonaObservacion,CategoriaDelVisitante,Volumen, file_name,continuo, load_date)  FROM (SELECT  $1,$2,$3,$4,$5,$6,$7,$8, METADATA$FILENAME,''c'',to_timestamp_ntz(current_timestamp)  from ''@s3_stage/flux/continuo/'' ) pattern=''.*Diario_Municipio_202.*''  file_format = ''csv_format_flx''  on_error = ''continue'';
				COPY INTO STAGING.ST_FLX_DIARIO_NACIONALIDAD(Fecha,DiaDeLaSemana,Origen,Pais,ZonaObservacion,CategoriaDelVisitante,Volumen, file_name,continuo, load_date)  FROM (SELECT  $1,$2,$3,$4,$5,$6,$7, METADATA$FILENAME,''c'',to_timestamp_ntz(current_timestamp)  from ''@s3_stage/flux/continuo/'' ) pattern=''.*Diario_Nacionalidad_202.*''  file_format = ''csv_format_flx''  on_error = ''continue'';
				COPY INTO STAGING.ST_FLX_DIARIO_MES(Mes,EtiquetaDelMes,Origen,ZonaObservacion,CategoriaDelVisitante,Volumen, file_name,continuo, load_date)  FROM (SELECT  $1,$2,$3,$4,$5,$6, METADATA$FILENAME,''c'',to_timestamp_ntz(current_timestamp)  from ''@s3_stage/flux/continuo/'' ) pattern=''.*Diario_Mes_202.*''  file_format = ''csv_format_flx''  on_error = ''continue'';
				COPY INTO STAGING.ST_FLX_DIARIO_MES_EDAD(Mes,EtiquetaDelMes,Origen,Edad,ZonaObservacion,CategoriaDelVisitante,Volumen, file_name,continuo, load_date)  FROM (SELECT  $1,$2,$3,$4,$5,$6,$7, METADATA$FILENAME,''c'',to_timestamp_ntz(current_timestamp)  from ''@s3_stage/flux/continuo/'' ) pattern=''.*Diario_Mes_Edad_202.*''  file_format = ''csv_format_flx''  on_error = ''continue'';
				COPY INTO STAGING.ST_FLX_DIARIO_MES_GENERO(Mes,EtiquetaDelMes,Origen,Genero,ZonaObservacion,CategoriaDelVisitante,Volumen, file_name,continuo, load_date)  FROM (SELECT  $1,$2,$3,$4,$5,$6,$7, METADATA$FILENAME,''c'',to_timestamp_ntz(current_timestamp)  from ''@s3_stage/flux/continuo/'' ) pattern=''.*Diario_Mes_Genero_202.*''  file_format = ''csv_format_flx''  on_error = ''continue'';
				COPY INTO STAGING.ST_FLX_DIARIO_MES_MUNICIPIO(Mes,EtiquetaDelMes,Origen,NombreMunicipio,NombreProvincia,ZonaObservacion,CategoriaDelVisitante,Volumen, file_name,continuo, load_date)  FROM (SELECT  $1,$2,$3,$4,$5,$6,$7,$8, METADATA$FILENAME,''c'',to_timestamp_ntz(current_timestamp)  from ''@s3_stage/flux/continuo/'' ) pattern=''.*Diario_Mes_Municipio_202.*''  file_format = ''csv_format_flx''  on_error = ''continue'';
				COPY INTO STAGING.ST_FLX_DIARIO_MES_NACIONALIDAD(Mes,EtiquetaDelMes,Origen,Pais,ZonaObservacion,CategoriaDelVisitante,Volumen, file_name,continuo, load_date)  FROM (SELECT  $1,$2,$3,$4,$5,$6,$7, METADATA$FILENAME,''c'',to_timestamp_ntz(current_timestamp)  from ''@s3_stage/flux/continuo/'' ) pattern=''.*Diario_Mes_Nacionalidad_202.*''  file_format = ''csv_format_flx''  on_error = ''continue'';
				COPY INTO STAGING.ST_FLX_DIARIO_2H(Fecha,DiaDeLaSemana,Origen,ZonaObservacion,CategoriaDelVisitante,Hora,Volumen, file_name,continuo, load_date)  FROM (SELECT  $1,$2,$3,$4,$5,$6,$7, METADATA$FILENAME,''c'',to_timestamp_ntz(current_timestamp)  from ''@s3_stage/flux/continuo/'' ) pattern=''.*Diario_2H_202.*''  file_format = ''csv_format_flx''  on_error = ''continue'';
				COPY INTO STAGING.ST_FLX_DIARIO_2H_MUNICIPIO(Fecha,DiaDeLaSemana,Origen,NombreMunicipio,NombreProvincia,ZonaObservacion,CategoriaDelVisitante,Hora,Volumen, file_name,continuo, load_date)  FROM (SELECT  $1,$2,$3,$4,$5,$6,$7,$8,$9, METADATA$FILENAME,''c'',to_timestamp_ntz(current_timestamp)  from ''@s3_stage/flux/continuo/'' ) pattern=''.*Diario_2H_Municipio_202.*''  file_format = ''csv_format_flx''  on_error = ''continue'';
				COPY INTO STAGING.ST_FLX_DIARIO_2H_NACIONALIDAD(Fecha,DiaDeLaSemana,Origen,Pais,ZonaObservacion,CategoriaDelVisitante,Hora,Volumen, file_name,continuo, load_date)  FROM (SELECT  $1,$2,$3,$4,$5,$6,$7,$8, METADATA$FILENAME,''c'',to_timestamp_ntz(current_timestamp)  from ''@s3_stage/flux/continuo/'' ) pattern=''.*Diario_2H_Nacionalidad_202.*''  file_format = ''csv_format_flx''  on_error = ''continue'';
				COPY INTO STAGING.ST_FLX_DURACIONESTANCIA(Fecha,DiaDeLaSemana,Origen,ZonaObservacion,CategoriaDelVisitante,DuracionDeLaEstancia,Volumen, file_name,continuo, load_date)  FROM (SELECT  $1,$2,$3,$4,$5,$6,$7, METADATA$FILENAME,''c'',to_timestamp_ntz(current_timestamp)  from ''@s3_stage/flux/continuo/'' ) pattern=''.*DuracionEstancia_202.*''  file_format = ''csv_format_flx''  on_error = ''continue'';
				COPY INTO STAGING.ST_FLX_DURACIONESTANCIA_MUNICIPIO(Fecha,DiaDeLaSemana,Origen,NombreMunicipio,NombreProvincia,ZonaObservacion,CategoriaDelVisitante,DuracionDeLaEstancia,Volumen, file_name,continuo, load_date)  FROM (SELECT  $1,$2,$3,$4,$5,$6,$7,$8,$9, METADATA$FILENAME,''c'',to_timestamp_ntz(current_timestamp)  from ''@s3_stage/flux/continuo/'' ) pattern=''.*DuracionEstancia_Municipio_202.*''  file_format = ''csv_format_flx''  on_error = ''continue'';
				COPY INTO STAGING.ST_FLX_DURACIONESTANCIA_NACIONALIDAD(Fecha,DiaDeLaSemana,Origen,Pais,ZonaObservacion,CategoriaDelVisitante,DuracionDeLaEstancia,Volumen, file_name,continuo, load_date)  FROM (SELECT  $1,$2,$3,$4,$5,$6,$7,$8, METADATA$FILENAME,''c'',to_timestamp_ntz(current_timestamp)  from ''@s3_stage/flux/continuo/'' ) pattern=''.*DuracionEstancia_Nacionalidad_202.*''  file_format = ''csv_format_flx''  on_error = ''continue'';
				COPY INTO STAGING.ST_FLX_LLEGADA(Fecha,DiaDeLaSemana,Origen,ZonaObservacion,CategoriaDelVisitante,Volumen, file_name,continuo, load_date)  FROM (SELECT  $1,$2,$3,$4,$5,$6, METADATA$FILENAME,''c'',to_timestamp_ntz(current_timestamp)  from ''@s3_stage/flux/continuo/'' ) pattern=''.*Llegada_202.*''  file_format = ''csv_format_flx''  on_error = ''continue'';
				COPY INTO STAGING.ST_FLX_LLEGADA_EDAD(Fecha,DiaDeLaSemana,Origen,Edad,ZonaObservacion,CategoriaDelVisitante,Volumen, file_name,continuo, load_date)  FROM (SELECT  $1,$2,$3,$4,$5,$6,$7, METADATA$FILENAME,''c'',to_timestamp_ntz(current_timestamp)  from ''@s3_stage/flux/continuo/'' ) pattern=''.*Llegada_Edad_202.*''  file_format = ''csv_format_flx''  on_error = ''continue'';
				COPY INTO STAGING.ST_FLX_LLEGADA_GENERO(Fecha,DiaDeLaSemana,Origen,Genero,ZonaObservacion,CategoriaDelVisitante,Volumen, file_name,continuo, load_date)  FROM (SELECT  $1,$2,$3,$4,$5,$6,$7, METADATA$FILENAME,''c'',to_timestamp_ntz(current_timestamp)  from ''@s3_stage/flux/continuo/'' ) pattern=''.*Llegada_Genero_202.*''  file_format = ''csv_format_flx''  on_error = ''continue'';
				COPY INTO STAGING.ST_FLX_LLEGADA_MUNICIPIO(Fecha,DiaDeLaSemana,Origen,NombreMunicipio,NombreProvincia,ZonaObservacion,CategoriaDelVisitante,Volumen, file_name,continuo, load_date)  FROM (SELECT  $1,$2,$3,$4,$5,$6,$7,$8, METADATA$FILENAME,''c'',to_timestamp_ntz(current_timestamp)  from ''@s3_stage/flux/continuo/'' ) pattern=''.*Llegada_Municipio_202.*''  file_format = ''csv_format_flx''  on_error = ''continue'';
				COPY INTO STAGING.ST_FLX_LLEGADA_NACIONALIDAD(Fecha,DiaDeLaSemana,Origen,Pais,ZonaObservacion,CategoriaDelVisitante,Volumen, file_name,continuo, load_date)  FROM (SELECT  $1,$2,$3,$4,$5,$6,$7, METADATA$FILENAME,''c'',to_timestamp_ntz(current_timestamp)  from ''@s3_stage/flux/continuo/'' ) pattern=''.*Llegada_Nacionalidad_202.*''  file_format = ''csv_format_flx''  on_error = ''continue'';
				COPY INTO STAGING.ST_FLX_SALIDA(Fecha,DiaDeLaSemana,Origen,ZonaObservacion,CategoriaDelVisitante,Volumen, file_name,continuo, load_date)  FROM (SELECT  $1,$2,$3,$4,$5,$6, METADATA$FILENAME,''c'',to_timestamp_ntz(current_timestamp)  from ''@s3_stage/flux/continuo/'' ) pattern=''.*Salida_202.*''  file_format = ''csv_format_flx''  on_error = ''continue'';
				COPY INTO STAGING.ST_FLX_SALIDA_EDAD(Fecha,DiaDeLaSemana,Origen,Edad,ZonaObservacion,CategoriaDelVisitante,Volumen, file_name,continuo, load_date)  FROM (SELECT  $1,$2,$3,$4,$5,$6,$7, METADATA$FILENAME,''c'',to_timestamp_ntz(current_timestamp)  from ''@s3_stage/flux/continuo/'' ) pattern=''.*Salida_Edad_202.*''  file_format = ''csv_format_flx''  on_error = ''continue'';
				COPY INTO STAGING.ST_FLX_SALIDA_GENERO(Fecha,DiaDeLaSemana,Origen,Genero,ZonaObservacion,CategoriaDelVisitante,Volumen, file_name,continuo, load_date)  FROM (SELECT  $1,$2,$3,$4,$5,$6,$7, METADATA$FILENAME,''c'',to_timestamp_ntz(current_timestamp)  from ''@s3_stage/flux/continuo/'' ) pattern=''.*Salida_Genero_202.*''  file_format = ''csv_format_flx''  on_error = ''continue'';
				COPY INTO STAGING.ST_FLX_SALIDA_MUNICIPIO(Fecha,DiaDeLaSemana,Origen,NombreMunicipio,NombreProvincia,ZonaObservacion,CategoriaDelVisitante,Volumen, file_name,continuo, load_date)  FROM (SELECT  $1,$2,$3,$4,$5,$6,$7,$8, METADATA$FILENAME,''c'',to_timestamp_ntz(current_timestamp)  from ''@s3_stage/flux/continuo/'' ) pattern=''.*Salida_Municipio_202.*''  file_format = ''csv_format_flx''  on_error = ''continue'';
				COPY INTO STAGING.ST_FLX_SALIDA_NACIONALIDAD(Fecha,DiaDeLaSemana,Origen,Pais,ZonaObservacion,CategoriaDelVisitante,Volumen, file_name,continuo, load_date)  FROM (SELECT  $1,$2,$3,$4,$5,$6,$7, METADATA$FILENAME,''c'',to_timestamp_ntz(current_timestamp)  from ''@s3_stage/flux/continuo/'' ) pattern=''.*Salida_Nacionalidad_202.*''  file_format = ''csv_format_flx''  on_error = ''continue'';
				COPY INTO STAGING.ST_FLX_LUGARACTIVIDAD_DIAVISITA(Fecha,DiaDeLaSemana,Origen,ZonaObservacion,CategoriaDelVisitante,MunicipioZonaDiariaDiaVisita,ProvinciaZonaDiariaDiaVisita,Volumen, file_name,continuo, load_date)  FROM (SELECT  $1,$2,$3,$4,$5,$6,$7,$8, METADATA$FILENAME,''c'',to_timestamp_ntz(current_timestamp)  from ''@s3_stage/flux/continuo/'' ) pattern=''.*LugarActividad_DiaVisita_202.*''  file_format = ''csv_format_flx''  on_error = ''continue'';
				COPY INTO STAGING.ST_FLX_LUGARACTIVIDAD_DIAVISITA_MUNICIPIO(Fecha,DiaDeLaSemana,Origen,NombreMunicipio,NombreProvincia,ZonaObservacion,CategoriaDelVisitante,MunicipioZonaDiariaDiaVisita,ProvinciaZonaDiariaDiaVisita,Volumen, file_name,continuo, load_date)  FROM (SELECT  $1,$2,$3,$4,$5,$6,$7,$8,$9,$10, METADATA$FILENAME,''c'',to_timestamp_ntz(current_timestamp)  from ''@s3_stage/flux/continuo/'' ) pattern=''.*LugarActividad_DiaVisita_Municipio_202.*''  file_format = ''csv_format_flx''  on_error = ''continue'';
				COPY INTO STAGING.ST_FLX_LUGARACTIVIDAD_DIAVISITA_NACIONALIDAD(Fecha,DiaDeLaSemana,Origen,Pais,ZonaObservacion,CategoriaDelVisitante,MunicipioZonaDiariaDiaVisita,ProvinciaZonaDiariaDiaVisita,Volumen, file_name,continuo, load_date)  FROM (SELECT  $1,$2,$3,$4,$5,$6,$7,$8,$9, METADATA$FILENAME,''c'',to_timestamp_ntz(current_timestamp)  from ''@s3_stage/flux/continuo/'' ) pattern=''.*LugarActividad_DiaVisita_Nacionalidad_202.*''  file_format = ''csv_format_flx''  on_error = ''continue'';
				COPY INTO STAGING.ST_FLX_LUGARACTIVIDAD_DIAVISITA_SEMANA(Semana,Origen,ZonaObservacion,CategoriaDelVisitante,MunicipioZonaDiariaDiaVisita,ProvinciaZonaDiariaDiaVisita,Volumen, file_name,continuo, load_date)  FROM (SELECT  $1,$2,$3,$4,$5,$6,$7, METADATA$FILENAME,''c'',to_timestamp_ntz(current_timestamp)  from ''@s3_stage/flux/continuo/'' ) pattern=''.*LugarActividad_DiaVisita_Semana_202.*''  file_format = ''csv_format_flx''  on_error = ''continue'';
				COPY INTO STAGING.ST_FLX_LUGARACTIVIDAD_DIAVISITA_MUNICIPIO_SEMANA(Semana,Origen,NombreMunicipio,NombreProvincia,ZonaObservacion,CategoriaDelVisitante,MunicipioZonaDiariaDiaVisita,ProvinciaZonaDiariaDiaVisita,Volumen, file_name,continuo, load_date)  FROM (SELECT  $1,$2,$3,$4,$5,$6,$7,$8,$9, METADATA$FILENAME,''c'',to_timestamp_ntz(current_timestamp)  from ''@s3_stage/flux/continuo/'' ) pattern=''.*LugarActividad_DiaVisita_Municipio_Semana_202.*''  file_format = ''csv_format_flx''  on_error = ''continue'';
				COPY INTO STAGING.ST_FLX_LUGARACTIVIDAD_DIAVISITA_NACIONALIDAD_SEMANA(Semana,Origen,Pais,ZonaObservacion,CategoriaDelVisitante,MunicipioZonaDiariaDiaVisita,ProvinciaZonaDiariaDiaVisita,Volumen, file_name,continuo, load_date)  FROM (SELECT  $1,$2,$3,$4,$5,$6,$7,$8, METADATA$FILENAME,''c'',to_timestamp_ntz(current_timestamp)  from ''@s3_stage/flux/continuo/'' ) pattern=''.*LugarActividad_DiaVisita_Nacionalidad_Semana_202.*''  file_format = ''csv_format_flx''  on_error = ''continue'';
				COPY INTO STAGING.ST_FLX_LUGARACTIVIDAD_VISPERA(Fecha,DiaDeLaSemana,Origen,ZonaObservacion,CategoriaDelVisitante,MunicipioZonaDiariaVispera,ProvinciaZonaDiariaVispera,Volumen, file_name,continuo, load_date)  FROM (SELECT  $1,$2,$3,$4,$5,$6,$7,$8, METADATA$FILENAME,''c'',to_timestamp_ntz(current_timestamp)  from ''@s3_stage/flux/continuo/'' ) pattern=''.*LugarActividad_Vispera_202.*''  file_format = ''csv_format_flx''  on_error = ''continue'';
				COPY INTO STAGING.ST_FLX_LUGARACTIVIDAD_VISPERA_MUNICIPIO(Fecha,DiaDeLaSemana,Origen,NombreMunicipio,NombreProvincia,ZonaObservacion,CategoriaDelVisitante,MunicipioZonaDiariaVispera,ProvinciaZonaDiariaVispera,Volumen, file_name,continuo, load_date)  FROM (SELECT  $1,$2,$3,$4,$5,$6,$7,$8,$9,$10, METADATA$FILENAME,''c'',to_timestamp_ntz(current_timestamp)  from ''@s3_stage/flux/continuo/'' ) pattern=''.*LugarActividad_Vispera_Municipio_202.*''  file_format = ''csv_format_flx''  on_error = ''continue'';
				COPY INTO STAGING.ST_FLX_LUGARACTIVIDAD_VISPERA_NACIONALIDAD(Fecha,DiaDeLaSemana,Origen,Pais,ZonaObservacion,CategoriaDelVisitante,MunicipioZonaDiariaVispera,ProvinciaZonaDiariaVispera,Volumen, file_name,continuo, load_date)  FROM (SELECT  $1,$2,$3,$4,$5,$6,$7,$8,$9, METADATA$FILENAME,''c'',to_timestamp_ntz(current_timestamp)  from ''@s3_stage/flux/continuo/'' ) pattern=''.*LugarActividad_Vispera_Nacionalidad_202.*''  file_format = ''csv_format_flx''  on_error = ''continue'';
				COPY INTO STAGING.ST_FLX_LUGARACTIVIDAD_VISPERA_SEMANA(Semana,Origen,ZonaObservacion,CategoriaDelVisitante,MunicipioZonaDiariaVispera,ProvinciaZonaDiariaVispera,Volumen, file_name,continuo, load_date)  FROM (SELECT  $1,$2,$3,$4,$5,$6,$7, METADATA$FILENAME,''c'',to_timestamp_ntz(current_timestamp)  from ''@s3_stage/flux/continuo/'' ) pattern=''.*LugarActividad_Vispera_Semana_202.*''  file_format = ''csv_format_flx''  on_error = ''continue'';
				COPY INTO STAGING.ST_FLX_LUGARACTIVIDAD_VISPERA_MUNICIPIO_SEMANA(Semana,Origen,NombreMunicipio,NombreProvincia,ZonaObservacion,CategoriaDelVisitante,MunicipioZonaDiariaVispera,ProvinciaZonaDiariaVispera,Volumen, file_name,continuo, load_date)  FROM (SELECT  $1,$2,$3,$4,$5,$6,$7,$8,$9, METADATA$FILENAME,''c'',to_timestamp_ntz(current_timestamp)  from ''@s3_stage/flux/continuo/'' ) pattern=''.*LugarActividad_Vispera_Municipio_Semana_202.*''  file_format = ''csv_format_flx''  on_error = ''continue'';
				COPY INTO STAGING.ST_FLX_LUGARACTIVIDAD_VISPERA_NACIONALIDAD_SEMANA(Semana,Origen,Pais,ZonaObservacion,CategoriaDelVisitante,MunicipioZonaDiariaVispera,ProvinciaZonaDiariaVispera,Volumen, file_name,continuo, load_date)  FROM (SELECT  $1,$2,$3,$4,$5,$6,$7,$8, METADATA$FILENAME,''c'',to_timestamp_ntz(current_timestamp)  from ''@s3_stage/flux/continuo/'' ) pattern=''.*LugarActividad_Vispera_Nacionalidad_Semana_202.*''  file_format = ''csv_format_flx''  on_error = ''continue'';
				COPY INTO STAGING.ST_FLX_LUGARNOCHE_DIAVISITA(Fecha,DiaDeLaSemana,Origen,ZonaObservacion,CategoriaDelVisitante,MunicipioZonaPernoctacionDiaVisita,ProvinciaZonaPernoctacionDiaVisita,Volumen, file_name,continuo, load_date)  FROM (SELECT  $1,$2,$3,$4,$5,$6,$7,$8, METADATA$FILENAME,''c'',to_timestamp_ntz(current_timestamp)  from ''@s3_stage/flux/continuo/'' ) pattern=''.*LugarNoche_DiaVisita_202.*''  file_format = ''csv_format_flx''  on_error = ''continue'';
				COPY INTO STAGING.ST_FLX_LUGARNOCHE_DIAVISITA_MUNICIPIO(Fecha,DiaDeLaSemana,Origen,NombreMunicipio,NombreProvincia,ZonaObservacion,CategoriaDelVisitante,MunicipioZonaPernoctacionDiaVisita,ProvinciaZonaPernoctacionDiaVisita,Volumen, file_name,continuo, load_date)  FROM (SELECT  $1,$2,$3,$4,$5,$6,$7,$8,$9,$10, METADATA$FILENAME,''c'',to_timestamp_ntz(current_timestamp)  from ''@s3_stage/flux/continuo/'' ) pattern=''.*LugarNoche_DiaVisita_Municipio_202.*''  file_format = ''csv_format_flx''  on_error = ''continue'';
				COPY INTO STAGING.ST_FLX_LUGARNOCHE_DIAVISITA_MUNICIPIO_SEMANA(Semana,Origen,NombreMunicipio,NombreProvincia,ZonaObservacion,CategoriaDelVisitante,MunicipioZonaPernoctacionDiaVisita,ProvinciaZonaPernoctacionDiaVisita,Volumen, file_name,continuo, load_date)  FROM (SELECT  $1,$2,$3,$4,$5,$6,$7,$8,$9, METADATA$FILENAME,''c'',to_timestamp_ntz(current_timestamp)  from ''@s3_stage/flux/continuo/'' ) pattern=''.*LugarNoche_DiaVisita_Municipio_Semana_202.*''  file_format = ''csv_format_flx''  on_error = ''continue'';
				COPY INTO STAGING.ST_FLX_LUGARNOCHE_DIAVISITA_NACIONALIDAD(Fecha,DiaDeLaSemana,Origen,Pais,ZonaObservacion,CategoriaDelVisitante,MunicipioZonaPernoctacionDiaVisita,ProvinciaZonaPernoctacionDiaVisita,Volumen, file_name,continuo, load_date)  FROM (SELECT  $1,$2,$3,$4,$5,$6,$7,$8,$9, METADATA$FILENAME,''c'',to_timestamp_ntz(current_timestamp)  from ''@s3_stage/flux/continuo/'' ) pattern=''.*LugarNoche_DiaVisita_Nacionalidad_202.*''  file_format = ''csv_format_flx''  on_error = ''continue'';
				COPY INTO STAGING.ST_FLX_LUGARNOCHE_DIAVISITA_SEMANA(Semana,Origen,ZonaObservacion,CategoriaDelVisitante,MunicipioZonaPernoctacionDiaVisita,ProvinciaZonaPernoctacionDiaVisita,Volumen, file_name,continuo, load_date)  FROM (SELECT  $1,$2,$3,$4,$5,$6,$7, METADATA$FILENAME,''c'',to_timestamp_ntz(current_timestamp)  from ''@s3_stage/flux/continuo/'' ) pattern=''.*LugarNoche_DiaVisita_Semana_202.*''  file_format = ''csv_format_flx''  on_error = ''continue'';
				COPY INTO STAGING.ST_FLX_LUGARNOCHE_DIAVISITA_NACIONALIDAD_SEMANA(Semana,Origen,Pais,ZonaObservacion,CategoriaDelVisitante,MunicipioZonaPernoctacionDiaVisita,ProvinciaZonaPernoctacionDiaVisita,Volumen, file_name,continuo, load_date)  FROM (SELECT  $1,$2,$3,$4,$5,$6,$7,$8, METADATA$FILENAME,''c'',to_timestamp_ntz(current_timestamp)  from ''@s3_stage/flux/continuo/'' ) pattern=''.*LugarNoche_DiaVisita_Nacionalidad_Semana_202.*''  file_format = ''csv_format_flx''  on_error = ''continue'';
				COPY INTO STAGING.ST_FLX_LUGARNOCHE_VISPERA(Fecha,DiaDeLaSemana,Origen,ZonaObservacion,CategoriaDelVisitante,MunicipioZonaPernoctacionVispera,ProvinciaZonaPernoctacionVispera,Volumen, file_name,continuo, load_date)  FROM (SELECT  $1,$2,$3,$4,$5,$6,$7,$8, METADATA$FILENAME,''c'',to_timestamp_ntz(current_timestamp)  from ''@s3_stage/flux/continuo/'' ) pattern=''.*LugarNoche_Vispera_202.*''  file_format = ''csv_format_flx''  on_error = ''continue'';
				COPY INTO STAGING.ST_FLX_LUGARNOCHE_VISPERA_MUNICIPIO(Fecha,DiaDeLaSemana,Origen,NombreMunicipio,NombreProvincia,ZonaObservacion,CategoriaDelVisitante,MunicipioZonaPernoctacionVispera,ProvinciaZonaPernoctacionVispera,Volumen, file_name,continuo, load_date)  FROM (SELECT  $1,$2,$3,$4,$5,$6,$7,$8,$9,$10, METADATA$FILENAME,''c'',to_timestamp_ntz(current_timestamp)  from ''@s3_stage/flux/continuo/'' ) pattern=''.*LugarNoche_Vispera_Municipio_202.*''  file_format = ''csv_format_flx''  on_error = ''continue'';
				COPY INTO STAGING.ST_FLX_LUGARNOCHE_VISPERA_NACIONALIDAD(Fecha,DiaDeLaSemana,Origen,Pais,ZonaObservacion,CategoriaDelVisitante,MunicipioZonaPernoctacionVispera,ProvinciaZonaPernoctacionVispera,Volumen, file_name,continuo, load_date)  FROM (SELECT  $1,$2,$3,$4,$5,$6,$7,$8,$9, METADATA$FILENAME,''c'',to_timestamp_ntz(current_timestamp)  from ''@s3_stage/flux/continuo/'' ) pattern=''.*LugarNoche_Vispera_Nacionalidad_202.*''  file_format = ''csv_format_flx''  on_error = ''continue'';
				COPY INTO STAGING.ST_FLX_LUGARNOCHE_VISPERA_SEMANA(Semana,Origen,ZonaObservacion,CategoriaDelVisitante,MunicipioZonaPernoctacionVispera,ProvinciaZonaPernoctacionVispera,Volumen, file_name,continuo, load_date)  FROM (SELECT  $1,$2,$3,$4,$5,$6,$7, METADATA$FILENAME,''c'',to_timestamp_ntz(current_timestamp)  from ''@s3_stage/flux/continuo/'' ) pattern=''.*LugarNoche_Vispera_Semana_202.*''  file_format = ''csv_format_flx''  on_error = ''continue'';
				COPY INTO STAGING.ST_FLX_LUGARNOCHE_VISPERA_MUNICIPIO_SEMANA(Semana,Origen,NombreMunicipio,NombreProvincia,ZonaObservacion,CategoriaDelVisitante,MunicipioZonaPernoctacionVispera,ProvinciaZonaPernoctacionVispera,Volumen, file_name,continuo, load_date)  FROM (SELECT  $1,$2,$3,$4,$5,$6,$7,$8,$9, METADATA$FILENAME,''c'',to_timestamp_ntz(current_timestamp)  from ''@s3_stage/flux/continuo/'' ) pattern=''.*LugarNoche_Vispera_Municipio_Semana_202.*''  file_format = ''csv_format_flx''  on_error = ''continue'';
				COPY INTO STAGING.ST_FLX_LUGARNOCHE_VISPERA_NACIONALIDAD_SEMANA(Semana,Origen,Pais,ZonaObservacion,CategoriaDelVisitante,MunicipioZonaPernoctacionVispera,ProvinciaZonaPernoctacionVispera,Volumen, file_name,continuo, load_date)  FROM (SELECT  $1,$2,$3,$4,$5,$6,$7,$8, METADATA$FILENAME,''c'',to_timestamp_ntz(current_timestamp)  from ''@s3_stage/flux/continuo/'' ) pattern=''.*LugarNoche_Vispera_Nacionalidad_Semana_202.*''  file_format = ''csv_format_flx''  on_error = ''continue'';
				COPY INTO STAGING.ST_FLX_NOCHEESTANCIA(Fecha,DiaDeLaSemana,Origen,ZonaObservacion,CategoriaDelVisitante,DuracionEstancia,DuracionEstanciaNum,Volumen, file_name,continuo, load_date)  FROM (SELECT  $1,$2,$3,$4,$5,$6,$7,$8, METADATA$FILENAME,''c'',to_timestamp_ntz(current_timestamp)  from ''@s3_stage/flux/continuo/'' ) pattern=''.*NocheEstancia_202.*''  file_format = ''csv_format_flx''  on_error = ''continue'';
				COPY INTO STAGING.ST_FLX_NOCHEESTANCIA_MUNICIPIO(Fecha,DiaDeLaSemana,Origen,NombreMunicipio,NombreProvincia,ZonaObservacion,CategoriaDelVisitante,DuracionEstancia,DuracionEstanciaNum,Volumen, file_name,continuo, load_date)  FROM (SELECT  $1,$2,$3,$4,$5,$6,$7,$8,$9,$10, METADATA$FILENAME,''c'',to_timestamp_ntz(current_timestamp)  from ''@s3_stage/flux/continuo/'' ) pattern=''.*NocheEstancia_Municipio_202.*''  file_format = ''csv_format_flx''  on_error = ''continue'';
				COPY INTO STAGING.ST_FLX_NOCHEESTANCIA_NACIONALIDAD(Fecha,DiaDeLaSemana,Origen,Pais,ZonaObservacion,CategoriaDelVisitante,DuracionEstancia,DuracionEstanciaNum,Volumen, file_name,continuo, load_date)  FROM (SELECT  $1,$2,$3,$4,$5,$6,$7,$8,$9, METADATA$FILENAME,''c'',to_timestamp_ntz(current_timestamp)  from ''@s3_stage/flux/continuo/'' ) pattern=''.*NocheEstancia_Nacionalidad_202.*''  file_format = ''csv_format_flx''  on_error = ''continue'';
				COPY INTO STAGING.ST_FLX_NOCTURNO(Fecha,DiaDeLaSemana,Origen,ZonaObservacion,CategoriaDelVisitante,Volumen, file_name,continuo, load_date)  FROM (SELECT  $1,$2,$3,$4,$5,$6, METADATA$FILENAME,''c'',to_timestamp_ntz(current_timestamp)  from ''@s3_stage/flux/continuo/'' ) pattern=''.*Nocturno_202.*''  file_format = ''csv_format_flx''  on_error = ''continue'';
				COPY INTO STAGING.ST_FLX_NOCTURNO_EDAD(Fecha,DiaDeLaSemana,Origen,Edad,ZonaObservacion,CategoriaDelVisitante,Volumen, file_name,continuo, load_date)  FROM (SELECT  $1,$2,$3,$4,$5,$6,$7, METADATA$FILENAME,''c'',to_timestamp_ntz(current_timestamp)  from ''@s3_stage/flux/continuo/'' ) pattern=''.*Nocturno_Edad_202.*''  file_format = ''csv_format_flx''  on_error = ''continue'';
				COPY INTO STAGING.ST_FLX_NOCTURNO_GENERO(Fecha,DiaDeLaSemana,Origen,Genero,ZonaObservacion,CategoriaDelVisitante,Volumen, file_name,continuo, load_date)  FROM (SELECT  $1,$2,$3,$4,$5,$6,$7, METADATA$FILENAME,''c'',to_timestamp_ntz(current_timestamp)  from ''@s3_stage/flux/continuo/'' ) pattern=''.*Nocturno_Genero_202.*''  file_format = ''csv_format_flx''  on_error = ''continue'';
				COPY INTO STAGING.ST_FLX_NOCTURNO_MUNICIPIO(Fecha,DiaDeLaSemana,Origen,NombreMunicipio,NombreProvincia,ZonaObservacion,CategoriaDelVisitante,Volumen, file_name,continuo, load_date)  FROM (SELECT  $1,$2,$3,$4,$5,$6,$7,$8, METADATA$FILENAME,''c'',to_timestamp_ntz(current_timestamp)  from ''@s3_stage/flux/continuo/'' ) pattern=''.*Nocturno_Municipio_202.*''  file_format = ''csv_format_flx''  on_error = ''continue'';
				COPY INTO STAGING.ST_FLX_NOCTURNO_NACIONALIDAD(Fecha,DiaDeLaSemana,Origen,Pais,ZonaObservacion,CategoriaDelVisitante,Volumen, file_name,continuo, load_date)  FROM (SELECT  $1,$2,$3,$4,$5,$6,$7, METADATA$FILENAME,''c'',to_timestamp_ntz(current_timestamp)  from ''@s3_stage/flux/continuo/'' ) pattern=''.*Nocturno_Nacionalidad_202.*''  file_format = ''csv_format_flx''  on_error = ''continue'';
				COPY INTO STAGING.ST_FLX_NOCTURNO_MES(Mes,EtiquetaDelMes,Origen,ZonaObservacion,CategoriaDelVisitante,Volumen, file_name,continuo, load_date)  FROM (SELECT  $1,$2,$3,$4,$5,$6, METADATA$FILENAME,''c'',to_timestamp_ntz(current_timestamp)  from ''@s3_stage/flux/continuo/'' ) pattern=''.*Nocturno_Mes_202.*''  file_format = ''csv_format_flx''  on_error = ''continue'';
				COPY INTO STAGING.ST_FLX_NOCTURNO_MES_EDAD(Mes,EtiquetaDelMes,Origen,Edad,ZonaObservacion,CategoriaDelVisitante,Volumen, file_name,continuo, load_date)  FROM (SELECT  $1,$2,$3,$4,$5,$6,$7, METADATA$FILENAME,''c'',to_timestamp_ntz(current_timestamp)  from ''@s3_stage/flux/continuo/'' ) pattern=''.*Nocturno_Mes_Edad_202.*''  file_format = ''csv_format_flx''  on_error = ''continue'';
				COPY INTO STAGING.ST_FLX_NOCTURNO_MES_GENERO(Mes,EtiquetaDelMes,Origen,Genero,ZonaObservacion,CategoriaDelVisitante,Volumen, file_name,continuo, load_date)  FROM (SELECT  $1,$2,$3,$4,$5,$6,$7, METADATA$FILENAME,''c'',to_timestamp_ntz(current_timestamp)  from ''@s3_stage/flux/continuo/'' ) pattern=''.*Nocturno_Mes_Genero_202.*''  file_format = ''csv_format_flx''  on_error = ''continue'';
				COPY INTO STAGING.ST_FLX_NOCTURNO_MES_MUNICIPIO(Mes,EtiquetaDelMes,Origen,NombreMunicipio,NombreProvincia,ZonaObservacion,CategoriaDelVisitante,Volumen, file_name,continuo, load_date)  FROM (SELECT  $1,$2,$3,$4,$5,$6,$7,$8, METADATA$FILENAME,''c'',to_timestamp_ntz(current_timestamp)  from ''@s3_stage/flux/continuo/'' ) pattern=''.*Nocturno_Mes_Municipio_202.*''  file_format = ''csv_format_flx''  on_error = ''continue'';
				COPY INTO STAGING.ST_FLX_NOCTURNO_MES_NACIONALIDAD(Mes,EtiquetaDelMes,Origen,Pais,ZonaObservacion,CategoriaDelVisitante,Volumen, file_name,continuo, load_date)  FROM (SELECT  $1,$2,$3,$4,$5,$6,$7, METADATA$FILENAME,''c'',to_timestamp_ntz(current_timestamp)  from ''@s3_stage/flux/continuo/'' ) pattern=''.*Nocturno_Mes_Nacionalidad_202.*''  file_format = ''csv_format_flx''  on_error = ''continue'';
				COPY INTO STAGING.ST_FLX_RECURRENCIA(Fecha,DiaDeLaSemana,Origen,ZonaObservacion,CategoriaDelVisitante,Recurrencia,Volumen, file_name,continuo, load_date)  FROM (SELECT  $1,$2,$3,$4,$5,$6,$7, METADATA$FILENAME,''c'',to_timestamp_ntz(current_timestamp)  from ''@s3_stage/flux/continuo/'' ) pattern=''.*Recurrencia_202.*''  file_format = ''csv_format_flx''  on_error = ''continue'';
				COPY INTO STAGING.ST_FLX_RECURRENCIA_MUNICIPIO(Fecha,DiaDeLaSemana,Origen,NombreMunicipio,NombreProvincia,ZonaObservacion,CategoriaDelVisitante,Recurrencia,Volumen, file_name,continuo, load_date)  FROM (SELECT  $1,$2,$3,$4,$5,$6,$7,$8,$9, METADATA$FILENAME,''c'',to_timestamp_ntz(current_timestamp)  from ''@s3_stage/flux/continuo/'' ) pattern=''.*Recurrencia_Municipio_202.*''  file_format = ''csv_format_flx''  on_error = ''continue'';
				COPY INTO STAGING.ST_FLX_RECURRENCIA_NACIONALIDAD(Fecha,DiaDeLaSemana,Origen,Pais,ZonaObservacion,CategoriaDelVisitante,Recurrencia,Volumen, file_name,continuo, load_date)  FROM (SELECT  $1,$2,$3,$4,$5,$6,$7,$8, METADATA$FILENAME,''c'',to_timestamp_ntz(current_timestamp)  from ''@s3_stage/flux/continuo/'' ) pattern=''.*Recurrencia_Nacionalidad_202.*''  file_format = ''csv_format_flx''  on_error = ''continue'';

		END;

		ALTER TASK STAGING.LOAD_FLX_CONTINUO RESUME;

        RETURN ''Create task STAGING.LOAD_FLX_CONTINUO & RESUME'';

    END;
';


EXECUTE IMMEDIATE '
    BEGIN		

		create or replace task DEV_TOURISM_DB.STAGING.LOAD_FLX_NOCONTINUO
			schedule=''USING CRON  0 11 * * * Europe/Madrid''
			USER_TASK_MANAGED_INITIAL_WAREHOUSE_SIZE=''XLARGE''
			as BEGIN
				COPY INTO STAGING.ST_FLX_DIARIO(Fecha,DiaDeLaSemana,Origen,ZonaObservacion,CategoriaDelVisitante,Volumen, file_name,continuo, load_date)  FROM (SELECT  $1,$2,$3,$4,$5,$6,METADATA$FILENAME,''nc'',to_timestamp_ntz(current_timestamp)  from ''@s3_stage/flux/nocontinuo/'' ) pattern=''.*Diario_L.*''  file_format = ''csv_format_flx''  on_error = ''continue'';
				COPY INTO STAGING.ST_FLX_DIARIO_EDAD(Fecha,DiaDeLaSemana,Origen,Edad,ZonaObservacion,CategoriaDelVisitante,Volumen, file_name,continuo, load_date)  FROM (SELECT  $1,$2,$3,$4,$5,$6,$7,METADATA$FILENAME,''nc'',to_timestamp_ntz(current_timestamp)  from ''@s3_stage/flux/nocontinuo/'' ) pattern=''.*Diario_Edad_L.*''  file_format = ''csv_format_flx''  on_error = ''continue'';
				COPY INTO STAGING.ST_FLX_DIARIO_GENERO(Fecha,DiaDeLaSemana,Origen,Genero,ZonaObservacion,CategoriaDelVisitante,Volumen, file_name,continuo, load_date)  FROM (SELECT  $1,$2,$3,$4,$5,$6,$7,METADATA$FILENAME,''nc'',to_timestamp_ntz(current_timestamp)  from ''@s3_stage/flux/nocontinuo/'' ) pattern=''.*Diario_Genero_L.*''  file_format = ''csv_format_flx''  on_error = ''continue'';
				COPY INTO STAGING.ST_FLX_DIARIO_MUNICIPIO(Fecha,DiaDeLaSemana,Origen,NombreMunicipio,NombreProvincia,ZonaObservacion,CategoriaDelVisitante,Volumen, file_name,continuo, load_date)  FROM (SELECT  $1,$2,$3,$4,$5,$6,$7,$8,METADATA$FILENAME,''nc'',to_timestamp_ntz(current_timestamp)  from ''@s3_stage/flux/nocontinuo/'' ) pattern=''.*Diario_Municipio_L.*''  file_format = ''csv_format_flx''  on_error = ''continue'';
				COPY INTO STAGING.ST_FLX_DIARIO_NACIONALIDAD(Fecha,DiaDeLaSemana,Origen,Pais,ZonaObservacion,CategoriaDelVisitante,Volumen, file_name,continuo, load_date)  FROM (SELECT  $1,$2,$3,$4,$5,$6,$7,METADATA$FILENAME,''nc'',to_timestamp_ntz(current_timestamp)  from ''@s3_stage/flux/nocontinuo/'' ) pattern=''.*Diario_Nacionalidad_L.*''  file_format = ''csv_format_flx''  on_error = ''continue'';
				COPY INTO STAGING.ST_FLX_DIARIO_MES(Mes,EtiquetaDelMes,Origen,ZonaObservacion,CategoriaDelVisitante,Volumen, file_name,continuo, load_date)  FROM (SELECT  $1,$2,$3,$4,$5,$6,METADATA$FILENAME,''nc'',to_timestamp_ntz(current_timestamp)  from ''@s3_stage/flux/nocontinuo/'' ) pattern=''.*Diario_Mes_L.*''  file_format = ''csv_format_flx''  on_error = ''continue'';
				COPY INTO STAGING.ST_FLX_DIARIO_MES_EDAD(Mes,EtiquetaDelMes,Origen,Edad,ZonaObservacion,CategoriaDelVisitante,Volumen, file_name,continuo, load_date)  FROM (SELECT  $1,$2,$3,$4,$5,$6,$7,METADATA$FILENAME,''nc'',to_timestamp_ntz(current_timestamp)  from ''@s3_stage/flux/nocontinuo/'' ) pattern=''.*Diario_Mes_Edad_L.*''  file_format = ''csv_format_flx''  on_error = ''continue'';
				COPY INTO STAGING.ST_FLX_DIARIO_MES_GENERO(Mes,EtiquetaDelMes,Origen,Genero,ZonaObservacion,CategoriaDelVisitante,Volumen, file_name,continuo, load_date)  FROM (SELECT  $1,$2,$3,$4,$5,$6,$7,METADATA$FILENAME,''nc'',to_timestamp_ntz(current_timestamp)  from ''@s3_stage/flux/nocontinuo/'' ) pattern=''.*Diario_Mes_Genero_L.*''  file_format = ''csv_format_flx''  on_error = ''continue'';
				COPY INTO STAGING.ST_FLX_DIARIO_MES_MUNICIPIO(Mes,EtiquetaDelMes,Origen,NombreMunicipio,NombreProvincia,ZonaObservacion,CategoriaDelVisitante,Volumen, file_name,continuo, load_date)  FROM (SELECT  $1,$2,$3,$4,$5,$6,$7,$8,METADATA$FILENAME,''nc'',to_timestamp_ntz(current_timestamp)  from ''@s3_stage/flux/nocontinuo/'' ) pattern=''.*Diario_Mes_Municipio_L.*''  file_format = ''csv_format_flx''  on_error = ''continue'';
				COPY INTO STAGING.ST_FLX_DIARIO_MES_NACIONALIDAD(Mes,EtiquetaDelMes,Origen,Pais,ZonaObservacion,CategoriaDelVisitante,Volumen, file_name,continuo, load_date)  FROM (SELECT  $1,$2,$3,$4,$5,$6,$7,METADATA$FILENAME,''nc'',to_timestamp_ntz(current_timestamp)  from ''@s3_stage/flux/nocontinuo/'' ) pattern=''.*Diario_Mes_Nacionalidad_L.*''  file_format = ''csv_format_flx''  on_error = ''continue'';
				COPY INTO STAGING.ST_FLX_DIARIO_2H(Fecha,DiaDeLaSemana,Origen,ZonaObservacion,CategoriaDelVisitante,Hora,Volumen, file_name,continuo, load_date)  FROM (SELECT  $1,$2,$3,$4,$5,$6,$7,METADATA$FILENAME,''nc'',to_timestamp_ntz(current_timestamp)  from ''@s3_stage/flux/nocontinuo/'' ) pattern=''.*Diario_2H_L.*''  file_format = ''csv_format_flx''  on_error = ''continue'';
				COPY INTO STAGING.ST_FLX_DIARIO_2H_MUNICIPIO(Fecha,DiaDeLaSemana,Origen,NombreMunicipio,NombreProvincia,ZonaObservacion,CategoriaDelVisitante,Hora,Volumen, file_name,continuo, load_date)  FROM (SELECT  $1,$2,$3,$4,$5,$6,$7,$8,$9,METADATA$FILENAME,''nc'',to_timestamp_ntz(current_timestamp)  from ''@s3_stage/flux/nocontinuo/'' ) pattern=''.*Diario_2H_Municipio_L.*''  file_format = ''csv_format_flx''  on_error = ''continue'';
				COPY INTO STAGING.ST_FLX_DIARIO_2H_NACIONALIDAD(Fecha,DiaDeLaSemana,Origen,Pais,ZonaObservacion,CategoriaDelVisitante,Hora,Volumen, file_name,continuo, load_date)  FROM (SELECT  $1,$2,$3,$4,$5,$6,$7,$8,METADATA$FILENAME,''nc'',to_timestamp_ntz(current_timestamp)  from ''@s3_stage/flux/nocontinuo/'' ) pattern=''.*Diario_2H_Nacionalidad_L.*''  file_format = ''csv_format_flx''  on_error = ''continue'';
				COPY INTO STAGING.ST_FLX_DURACIONESTANCIA(Fecha,DiaDeLaSemana,Origen,ZonaObservacion,CategoriaDelVisitante,DuracionDeLaEstancia,Volumen, file_name,continuo, load_date)  FROM (SELECT  $1,$2,$3,$4,$5,$6,$7,METADATA$FILENAME,''nc'',to_timestamp_ntz(current_timestamp)  from ''@s3_stage/flux/nocontinuo/'' ) pattern=''.*DuracionEstancia_L.*''  file_format = ''csv_format_flx''  on_error = ''continue'';
				COPY INTO STAGING.ST_FLX_DURACIONESTANCIA_MUNICIPIO(Fecha,DiaDeLaSemana,Origen,NombreMunicipio,NombreProvincia,ZonaObservacion,CategoriaDelVisitante,DuracionDeLaEstancia,Volumen, file_name,continuo, load_date)  FROM (SELECT  $1,$2,$3,$4,$5,$6,$7,$8,$9,METADATA$FILENAME,''nc'',to_timestamp_ntz(current_timestamp)  from ''@s3_stage/flux/nocontinuo/'' ) pattern=''.*DuracionEstancia_Municipio_L.*''  file_format = ''csv_format_flx''  on_error = ''continue'';
				COPY INTO STAGING.ST_FLX_DURACIONESTANCIA_NACIONALIDAD(Fecha,DiaDeLaSemana,Origen,Pais,ZonaObservacion,CategoriaDelVisitante,DuracionDeLaEstancia,Volumen, file_name,continuo, load_date)  FROM (SELECT  $1,$2,$3,$4,$5,$6,$7,$8,METADATA$FILENAME,''nc'',to_timestamp_ntz(current_timestamp)  from ''@s3_stage/flux/nocontinuo/'' ) pattern=''.*DuracionEstancia_Nacionalidad_L.*''  file_format = ''csv_format_flx''  on_error = ''continue'';
				COPY INTO STAGING.ST_FLX_LLEGADA(Fecha,DiaDeLaSemana,Origen,ZonaObservacion,CategoriaDelVisitante,Volumen, file_name,continuo, load_date)  FROM (SELECT  $1,$2,$3,$4,$5,$6,METADATA$FILENAME,''nc'',to_timestamp_ntz(current_timestamp)  from ''@s3_stage/flux/nocontinuo/'' ) pattern=''.*Llegada_L.*''  file_format = ''csv_format_flx''  on_error = ''continue'';
				COPY INTO STAGING.ST_FLX_LLEGADA_EDAD(Fecha,DiaDeLaSemana,Origen,Edad,ZonaObservacion,CategoriaDelVisitante,Volumen, file_name,continuo, load_date)  FROM (SELECT  $1,$2,$3,$4,$5,$6,$7,METADATA$FILENAME,''nc'',to_timestamp_ntz(current_timestamp)  from ''@s3_stage/flux/nocontinuo/'' ) pattern=''.*Llegada_Edad_L.*''  file_format = ''csv_format_flx''  on_error = ''continue'';
				COPY INTO STAGING.ST_FLX_LLEGADA_GENERO(Fecha,DiaDeLaSemana,Origen,Genero,ZonaObservacion,CategoriaDelVisitante,Volumen, file_name,continuo, load_date)  FROM (SELECT  $1,$2,$3,$4,$5,$6,$7,METADATA$FILENAME,''nc'',to_timestamp_ntz(current_timestamp)  from ''@s3_stage/flux/nocontinuo/'' ) pattern=''.*Llegada_Genero_L.*''  file_format = ''csv_format_flx''  on_error = ''continue'';
				COPY INTO STAGING.ST_FLX_LLEGADA_MUNICIPIO(Fecha,DiaDeLaSemana,Origen,NombreMunicipio,NombreProvincia,ZonaObservacion,CategoriaDelVisitante,Volumen, file_name,continuo, load_date)  FROM (SELECT  $1,$2,$3,$4,$5,$6,$7,$8,METADATA$FILENAME,''nc'',to_timestamp_ntz(current_timestamp)  from ''@s3_stage/flux/nocontinuo/'' ) pattern=''.*Llegada_Municipio_L.*''  file_format = ''csv_format_flx''  on_error = ''continue'';
				COPY INTO STAGING.ST_FLX_LLEGADA_NACIONALIDAD(Fecha,DiaDeLaSemana,Origen,Pais,ZonaObservacion,CategoriaDelVisitante,Volumen, file_name,continuo, load_date)  FROM (SELECT  $1,$2,$3,$4,$5,$6,$7,METADATA$FILENAME,''nc'',to_timestamp_ntz(current_timestamp)  from ''@s3_stage/flux/nocontinuo/'' ) pattern=''.*Llegada_Nacionalidad_L.*''  file_format = ''csv_format_flx''  on_error = ''continue'';
				COPY INTO STAGING.ST_FLX_SALIDA(Fecha,DiaDeLaSemana,Origen,ZonaObservacion,CategoriaDelVisitante,Volumen, file_name,continuo, load_date)  FROM (SELECT  $1,$2,$3,$4,$5,$6,METADATA$FILENAME,''nc'',to_timestamp_ntz(current_timestamp)  from ''@s3_stage/flux/nocontinuo/'' ) pattern=''.*Salida_L.*''  file_format = ''csv_format_flx''  on_error = ''continue'';
				COPY INTO STAGING.ST_FLX_SALIDA_EDAD(Fecha,DiaDeLaSemana,Origen,Edad,ZonaObservacion,CategoriaDelVisitante,Volumen, file_name,continuo, load_date)  FROM (SELECT  $1,$2,$3,$4,$5,$6,$7,METADATA$FILENAME,''nc'',to_timestamp_ntz(current_timestamp)  from ''@s3_stage/flux/nocontinuo/'' ) pattern=''.*Salida_Edad_L.*''  file_format = ''csv_format_flx''  on_error = ''continue'';
				COPY INTO STAGING.ST_FLX_SALIDA_GENERO(Fecha,DiaDeLaSemana,Origen,Genero,ZonaObservacion,CategoriaDelVisitante,Volumen, file_name,continuo, load_date)  FROM (SELECT  $1,$2,$3,$4,$5,$6,$7,METADATA$FILENAME,''nc'',to_timestamp_ntz(current_timestamp)  from ''@s3_stage/flux/nocontinuo/'' ) pattern=''.*Salida_Genero_L.*''  file_format = ''csv_format_flx''  on_error = ''continue'';
				COPY INTO STAGING.ST_FLX_SALIDA_MUNICIPIO(Fecha,DiaDeLaSemana,Origen,NombreMunicipio,NombreProvincia,ZonaObservacion,CategoriaDelVisitante,Volumen, file_name,continuo, load_date)  FROM (SELECT  $1,$2,$3,$4,$5,$6,$7,$8,METADATA$FILENAME,''nc'',to_timestamp_ntz(current_timestamp)  from ''@s3_stage/flux/nocontinuo/'' ) pattern=''.*Salida_Municipio_L.*''  file_format = ''csv_format_flx''  on_error = ''continue'';
				COPY INTO STAGING.ST_FLX_SALIDA_NACIONALIDAD(Fecha,DiaDeLaSemana,Origen,Pais,ZonaObservacion,CategoriaDelVisitante,Volumen, file_name,continuo, load_date)  FROM (SELECT  $1,$2,$3,$4,$5,$6,$7,METADATA$FILENAME,''nc'',to_timestamp_ntz(current_timestamp)  from ''@s3_stage/flux/nocontinuo/'' ) pattern=''.*Salida_Nacionalidad_L.*''  file_format = ''csv_format_flx''  on_error = ''continue'';
				COPY INTO STAGING.ST_FLX_LUGARACTIVIDAD_DIAVISITA(Fecha,DiaDeLaSemana,Origen,ZonaObservacion,CategoriaDelVisitante,MunicipioZonaDiariaDiaVisita,ProvinciaZonaDiariaDiaVisita,Volumen, file_name,continuo, load_date)  FROM (SELECT  $1,$2,$3,$4,$5,$6,$7,$8,METADATA$FILENAME,''nc'',to_timestamp_ntz(current_timestamp)  from ''@s3_stage/flux/nocontinuo/'' ) pattern=''.*LugarActividad_DiaVisita_L.*''  file_format = ''csv_format_flx''  on_error = ''continue'';
				COPY INTO STAGING.ST_FLX_LUGARACTIVIDAD_DIAVISITA_MUNICIPIO(Fecha,DiaDeLaSemana,Origen,NombreMunicipio,NombreProvincia,ZonaObservacion,CategoriaDelVisitante,MunicipioZonaDiariaDiaVisita,ProvinciaZonaDiariaDiaVisita,Volumen, file_name,continuo, load_date)  FROM (SELECT  $1,$2,$3,$4,$5,$6,$7,$8,$9,$10,METADATA$FILENAME,''nc'',to_timestamp_ntz(current_timestamp)  from ''@s3_stage/flux/nocontinuo/'' ) pattern=''.*LugarActividad_DiaVisita_Municipio_L.*''  file_format = ''csv_format_flx''  on_error = ''continue'';
				COPY INTO STAGING.ST_FLX_LUGARACTIVIDAD_DIAVISITA_NACIONALIDAD(Fecha,DiaDeLaSemana,Origen,Pais,ZonaObservacion,CategoriaDelVisitante,MunicipioZonaDiariaDiaVisita,ProvinciaZonaDiariaDiaVisita,Volumen, file_name,continuo, load_date)  FROM (SELECT  $1,$2,$3,$4,$5,$6,$7,$8,$9,METADATA$FILENAME,''nc'',to_timestamp_ntz(current_timestamp)  from ''@s3_stage/flux/nocontinuo/'' ) pattern=''.*LugarActividad_DiaVisita_Nacionalidad_L.*''  file_format = ''csv_format_flx''  on_error = ''continue'';
				COPY INTO STAGING.ST_FLX_LUGARACTIVIDAD_DIAVISITA_SEMANA(Semana,Origen,ZonaObservacion,CategoriaDelVisitante,MunicipioZonaDiariaDiaVisita,ProvinciaZonaDiariaDiaVisita,Volumen, file_name,continuo, load_date)  FROM (SELECT  $1,$2,$3,$4,$5,$6,$7,METADATA$FILENAME,''nc'',to_timestamp_ntz(current_timestamp)  from ''@s3_stage/flux/nocontinuo/'' ) pattern=''.*LugarActividad_DiaVisita_Semana_L.*''  file_format = ''csv_format_flx''  on_error = ''continue'';
				COPY INTO STAGING.ST_FLX_LUGARACTIVIDAD_DIAVISITA_MUNICIPIO_SEMANA(Semana,Origen,NombreMunicipio,NombreProvincia,ZonaObservacion,CategoriaDelVisitante,MunicipioZonaDiariaDiaVisita,ProvinciaZonaDiariaDiaVisita,Volumen, file_name,continuo, load_date)  FROM (SELECT  $1,$2,$3,$4,$5,$6,$7,$8,$9,METADATA$FILENAME,''nc'',to_timestamp_ntz(current_timestamp)  from ''@s3_stage/flux/nocontinuo/'' ) pattern=''.*LugarActividad_DiaVisita_Municipio_Semana_L.*''  file_format = ''csv_format_flx''  on_error = ''continue'';
				COPY INTO STAGING.ST_FLX_LUGARACTIVIDAD_DIAVISITA_NACIONALIDAD_SEMANA(Semana,Origen,Pais,ZonaObservacion,CategoriaDelVisitante,MunicipioZonaDiariaDiaVisita,ProvinciaZonaDiariaDiaVisita,Volumen, file_name,continuo, load_date)  FROM (SELECT  $1,$2,$3,$4,$5,$6,$7,$8,METADATA$FILENAME,''nc'',to_timestamp_ntz(current_timestamp)  from ''@s3_stage/flux/nocontinuo/'' ) pattern=''.*LugarActividad_DiaVisita_Nacionalidad_Semana_L.*''  file_format = ''csv_format_flx''  on_error = ''continue'';
				COPY INTO STAGING.ST_FLX_LUGARACTIVIDAD_VISPERA(Fecha,DiaDeLaSemana,Origen,ZonaObservacion,CategoriaDelVisitante,MunicipioZonaDiariaVispera,ProvinciaZonaDiariaVispera,Volumen, file_name,continuo, load_date)  FROM (SELECT  $1,$2,$3,$4,$5,$6,$7,$8,METADATA$FILENAME,''nc'',to_timestamp_ntz(current_timestamp)  from ''@s3_stage/flux/nocontinuo/'' ) pattern=''.*LugarActividad_Vispera_L.*''  file_format = ''csv_format_flx''  on_error = ''continue'';
				COPY INTO STAGING.ST_FLX_LUGARACTIVIDAD_VISPERA_MUNICIPIO(Fecha,DiaDeLaSemana,Origen,NombreMunicipio,NombreProvincia,ZonaObservacion,CategoriaDelVisitante,MunicipioZonaDiariaVispera,ProvinciaZonaDiariaVispera,Volumen, file_name,continuo, load_date)  FROM (SELECT  $1,$2,$3,$4,$5,$6,$7,$8,$9,$10,METADATA$FILENAME,''nc'',to_timestamp_ntz(current_timestamp)  from ''@s3_stage/flux/nocontinuo/'' ) pattern=''.*LugarActividad_Vispera_Municipio_L.*''  file_format = ''csv_format_flx''  on_error = ''continue'';
				COPY INTO STAGING.ST_FLX_LUGARACTIVIDAD_VISPERA_NACIONALIDAD(Fecha,DiaDeLaSemana,Origen,Pais,ZonaObservacion,CategoriaDelVisitante,MunicipioZonaDiariaVispera,ProvinciaZonaDiariaVispera,Volumen, file_name,continuo, load_date)  FROM (SELECT  $1,$2,$3,$4,$5,$6,$7,$8,$9,METADATA$FILENAME,''nc'',to_timestamp_ntz(current_timestamp)  from ''@s3_stage/flux/nocontinuo/'' ) pattern=''.*LugarActividad_Vispera_Nacionalidad_L.*''  file_format = ''csv_format_flx''  on_error = ''continue'';
				COPY INTO STAGING.ST_FLX_LUGARACTIVIDAD_VISPERA_SEMANA(Semana,Origen,ZonaObservacion,CategoriaDelVisitante,MunicipioZonaDiariaVispera,ProvinciaZonaDiariaVispera,Volumen, file_name,continuo, load_date)  FROM (SELECT  $1,$2,$3,$4,$5,$6,$7,METADATA$FILENAME,''nc'',to_timestamp_ntz(current_timestamp)  from ''@s3_stage/flux/nocontinuo/'' ) pattern=''.*LugarActividad_Vispera_Semana_L.*''  file_format = ''csv_format_flx''  on_error = ''continue'';
				COPY INTO STAGING.ST_FLX_LUGARACTIVIDAD_VISPERA_MUNICIPIO_SEMANA(Semana,Origen,NombreMunicipio,NombreProvincia,ZonaObservacion,CategoriaDelVisitante,MunicipioZonaDiariaVispera,ProvinciaZonaDiariaVispera,Volumen, file_name,continuo, load_date)  FROM (SELECT  $1,$2,$3,$4,$5,$6,$7,$8,$9,METADATA$FILENAME,''nc'',to_timestamp_ntz(current_timestamp)  from ''@s3_stage/flux/nocontinuo/'' ) pattern=''.*LugarActividad_Vispera_Municipio_Semana_L.*''  file_format = ''csv_format_flx''  on_error = ''continue'';
				COPY INTO STAGING.ST_FLX_LUGARACTIVIDAD_VISPERA_NACIONALIDAD_SEMANA(Semana,Origen,Pais,ZonaObservacion,CategoriaDelVisitante,MunicipioZonaDiariaVispera,ProvinciaZonaDiariaVispera,Volumen, file_name,continuo, load_date)  FROM (SELECT  $1,$2,$3,$4,$5,$6,$7,$8,METADATA$FILENAME,''nc'',to_timestamp_ntz(current_timestamp)  from ''@s3_stage/flux/nocontinuo/'' ) pattern=''.*LugarActividad_Vispera_Nacionalidad_Semana_L.*''  file_format = ''csv_format_flx''  on_error = ''continue'';
				COPY INTO STAGING.ST_FLX_LUGARNOCHE_DIAVISITA(Fecha,DiaDeLaSemana,Origen,ZonaObservacion,CategoriaDelVisitante,MunicipioZonaPernoctacionDiaVisita,ProvinciaZonaPernoctacionDiaVisita,Volumen, file_name,continuo, load_date)  FROM (SELECT  $1,$2,$3,$4,$5,$6,$7,$8,METADATA$FILENAME,''nc'',to_timestamp_ntz(current_timestamp)  from ''@s3_stage/flux/nocontinuo/'' ) pattern=''.*LugarNoche_DiaVisita_L.*''  file_format = ''csv_format_flx''  on_error = ''continue'';
				COPY INTO STAGING.ST_FLX_LUGARNOCHE_DIAVISITA_MUNICIPIO(Fecha,DiaDeLaSemana,Origen,NombreMunicipio,NombreProvincia,ZonaObservacion,CategoriaDelVisitante,MunicipioZonaPernoctacionDiaVisita,ProvinciaZonaPernoctacionDiaVisita,Volumen, file_name,continuo, load_date)  FROM (SELECT  $1,$2,$3,$4,$5,$6,$7,$8,$9,$10,METADATA$FILENAME,''nc'',to_timestamp_ntz(current_timestamp)  from ''@s3_stage/flux/nocontinuo/'' ) pattern=''.*LugarNoche_DiaVisita_Municipio_L.*''  file_format = ''csv_format_flx''  on_error = ''continue'';
				COPY INTO STAGING.ST_FLX_LUGARNOCHE_DIAVISITA_MUNICIPIO_SEMANA(Semana,Origen,NombreMunicipio,NombreProvincia,ZonaObservacion,CategoriaDelVisitante,MunicipioZonaPernoctacionDiaVisita,ProvinciaZonaPernoctacionDiaVisita,Volumen, file_name,continuo, load_date)  FROM (SELECT  $1,$2,$3,$4,$5,$6,$7,$8,$9,METADATA$FILENAME,''nc'',to_timestamp_ntz(current_timestamp)  from ''@s3_stage/flux/nocontinuo/'' ) pattern=''.*LugarNoche_DiaVisita_Municipio_Semana_L.*''  file_format = ''csv_format_flx''  on_error = ''continue'';
				COPY INTO STAGING.ST_FLX_LUGARNOCHE_DIAVISITA_NACIONALIDAD(Fecha,DiaDeLaSemana,Origen,Pais,ZonaObservacion,CategoriaDelVisitante,MunicipioZonaPernoctacionDiaVisita,ProvinciaZonaPernoctacionDiaVisita,Volumen, file_name,continuo, load_date)  FROM (SELECT  $1,$2,$3,$4,$5,$6,$7,$8,$9,METADATA$FILENAME,''nc'',to_timestamp_ntz(current_timestamp)  from ''@s3_stage/flux/nocontinuo/'' ) pattern=''.*LugarNoche_DiaVisita_Nacionalidad_L.*''  file_format = ''csv_format_flx''  on_error = ''continue'';
				COPY INTO STAGING.ST_FLX_LUGARNOCHE_DIAVISITA_SEMANA(Semana,Origen,ZonaObservacion,CategoriaDelVisitante,MunicipioZonaPernoctacionDiaVisita,ProvinciaZonaPernoctacionDiaVisita,Volumen, file_name,continuo, load_date)  FROM (SELECT  $1,$2,$3,$4,$5,$6,$7,METADATA$FILENAME,''nc'',to_timestamp_ntz(current_timestamp)  from ''@s3_stage/flux/nocontinuo/'' ) pattern=''.*LugarNoche_DiaVisita_Semana_L.*''  file_format = ''csv_format_flx''  on_error = ''continue'';
				COPY INTO STAGING.ST_FLX_LUGARNOCHE_DIAVISITA_NACIONALIDAD_SEMANA(Semana,Origen,Pais,ZonaObservacion,CategoriaDelVisitante,MunicipioZonaPernoctacionDiaVisita,ProvinciaZonaPernoctacionDiaVisita,Volumen, file_name,continuo, load_date)  FROM (SELECT  $1,$2,$3,$4,$5,$6,$7,$8,METADATA$FILENAME,''nc'',to_timestamp_ntz(current_timestamp)  from ''@s3_stage/flux/nocontinuo/'' ) pattern=''.*LugarNoche_DiaVisita_Nacionalidad_Semana_L.*''  file_format = ''csv_format_flx''  on_error = ''continue'';
				COPY INTO STAGING.ST_FLX_LUGARNOCHE_VISPERA(Fecha,DiaDeLaSemana,Origen,ZonaObservacion,CategoriaDelVisitante,MunicipioZonaPernoctacionVispera,ProvinciaZonaPernoctacionVispera,Volumen, file_name,continuo, load_date)  FROM (SELECT  $1,$2,$3,$4,$5,$6,$7,$8,METADATA$FILENAME,''nc'',to_timestamp_ntz(current_timestamp)  from ''@s3_stage/flux/nocontinuo/'' ) pattern=''.*LugarNoche_Vispera_L.*''  file_format = ''csv_format_flx''  on_error = ''continue'';
				COPY INTO STAGING.ST_FLX_LUGARNOCHE_VISPERA_MUNICIPIO(Fecha,DiaDeLaSemana,Origen,NombreMunicipio,NombreProvincia,ZonaObservacion,CategoriaDelVisitante,MunicipioZonaPernoctacionVispera,ProvinciaZonaPernoctacionVispera,Volumen, file_name,continuo, load_date)  FROM (SELECT  $1,$2,$3,$4,$5,$6,$7,$8,$9,$10,METADATA$FILENAME,''nc'',to_timestamp_ntz(current_timestamp)  from ''@s3_stage/flux/nocontinuo/'' ) pattern=''.*LugarNoche_Vispera_Municipio_L.*''  file_format = ''csv_format_flx''  on_error = ''continue'';
				COPY INTO STAGING.ST_FLX_LUGARNOCHE_VISPERA_NACIONALIDAD(Fecha,DiaDeLaSemana,Origen,Pais,ZonaObservacion,CategoriaDelVisitante,MunicipioZonaPernoctacionVispera,ProvinciaZonaPernoctacionVispera,Volumen, file_name,continuo, load_date)  FROM (SELECT  $1,$2,$3,$4,$5,$6,$7,$8,$9,METADATA$FILENAME,''nc'',to_timestamp_ntz(current_timestamp)  from ''@s3_stage/flux/nocontinuo/'' ) pattern=''.*LugarNoche_Vispera_Nacionalidad_L.*''  file_format = ''csv_format_flx''  on_error = ''continue'';
				COPY INTO STAGING.ST_FLX_LUGARNOCHE_VISPERA_SEMANA(Semana,Origen,ZonaObservacion,CategoriaDelVisitante,MunicipioZonaPernoctacionVispera,ProvinciaZonaPernoctacionVispera,Volumen, file_name,continuo, load_date)  FROM (SELECT  $1,$2,$3,$4,$5,$6,$7,METADATA$FILENAME,''nc'',to_timestamp_ntz(current_timestamp)  from ''@s3_stage/flux/nocontinuo/'' ) pattern=''.*LugarNoche_Vispera_Semana_L.*''  file_format = ''csv_format_flx''  on_error = ''continue'';
				COPY INTO STAGING.ST_FLX_LUGARNOCHE_VISPERA_MUNICIPIO_SEMANA(Semana,Origen,NombreMunicipio,NombreProvincia,ZonaObservacion,CategoriaDelVisitante,MunicipioZonaPernoctacionVispera,ProvinciaZonaPernoctacionVispera,Volumen, file_name,continuo, load_date)  FROM (SELECT  $1,$2,$3,$4,$5,$6,$7,$8,$9,METADATA$FILENAME,''nc'',to_timestamp_ntz(current_timestamp)  from ''@s3_stage/flux/nocontinuo/'' ) pattern=''.*LugarNoche_Vispera_Municipio_Semana_L.*''  file_format = ''csv_format_flx''  on_error = ''continue'';
				COPY INTO STAGING.ST_FLX_LUGARNOCHE_VISPERA_NACIONALIDAD_SEMANA(Semana,Origen,Pais,ZonaObservacion,CategoriaDelVisitante,MunicipioZonaPernoctacionVispera,ProvinciaZonaPernoctacionVispera,Volumen, file_name,continuo, load_date)  FROM (SELECT  $1,$2,$3,$4,$5,$6,$7,$8,METADATA$FILENAME,''nc'',to_timestamp_ntz(current_timestamp)  from ''@s3_stage/flux/nocontinuo/'' ) pattern=''.*LugarNoche_Vispera_Nacionalidad_Semana_L.*''  file_format = ''csv_format_flx''  on_error = ''continue'';
				COPY INTO STAGING.ST_FLX_NOCHEESTANCIA(Fecha,DiaDeLaSemana,Origen,ZonaObservacion,CategoriaDelVisitante,DuracionEstancia,DuracionEstanciaNum,Volumen, file_name,continuo, load_date)  FROM (SELECT  $1,$2,$3,$4,$5,$6,$7,$8,METADATA$FILENAME,''nc'',to_timestamp_ntz(current_timestamp)  from ''@s3_stage/flux/nocontinuo/'' ) pattern=''.*NocheEstancia_L.*''  file_format = ''csv_format_flx''  on_error = ''continue'';
				COPY INTO STAGING.ST_FLX_NOCHEESTANCIA_MUNICIPIO(Fecha,DiaDeLaSemana,Origen,NombreMunicipio,NombreProvincia,ZonaObservacion,CategoriaDelVisitante,DuracionEstancia,DuracionEstanciaNum,Volumen, file_name,continuo, load_date)  FROM (SELECT  $1,$2,$3,$4,$5,$6,$7,$8,$9,$10,METADATA$FILENAME,''nc'',to_timestamp_ntz(current_timestamp)  from ''@s3_stage/flux/nocontinuo/'' ) pattern=''.*NocheEstancia_Municipio_L.*''  file_format = ''csv_format_flx''  on_error = ''continue'';
				COPY INTO STAGING.ST_FLX_NOCHEESTANCIA_NACIONALIDAD(Fecha,DiaDeLaSemana,Origen,Pais,ZonaObservacion,CategoriaDelVisitante,DuracionEstancia,DuracionEstanciaNum,Volumen, file_name,continuo, load_date)  FROM (SELECT  $1,$2,$3,$4,$5,$6,$7,$8,$9,METADATA$FILENAME,''nc'',to_timestamp_ntz(current_timestamp)  from ''@s3_stage/flux/nocontinuo/'' ) pattern=''.*NocheEstancia_Nacionalidad_L.*''  file_format = ''csv_format_flx''  on_error = ''continue'';
				COPY INTO STAGING.ST_FLX_NOCTURNO(Fecha,DiaDeLaSemana,Origen,ZonaObservacion,CategoriaDelVisitante,Volumen, file_name,continuo, load_date)  FROM (SELECT  $1,$2,$3,$4,$5,$6,METADATA$FILENAME,''nc'',to_timestamp_ntz(current_timestamp)  from ''@s3_stage/flux/nocontinuo/'' ) pattern=''.*Nocturno_L.*''  file_format = ''csv_format_flx''  on_error = ''continue'';
				COPY INTO STAGING.ST_FLX_NOCTURNO_EDAD(Fecha,DiaDeLaSemana,Origen,Edad,ZonaObservacion,CategoriaDelVisitante,Volumen, file_name,continuo, load_date)  FROM (SELECT  $1,$2,$3,$4,$5,$6,$7,METADATA$FILENAME,''nc'',to_timestamp_ntz(current_timestamp)  from ''@s3_stage/flux/nocontinuo/'' ) pattern=''.*Nocturno_Edad_L.*''  file_format = ''csv_format_flx''  on_error = ''continue'';
				COPY INTO STAGING.ST_FLX_NOCTURNO_GENERO(Fecha,DiaDeLaSemana,Origen,Genero,ZonaObservacion,CategoriaDelVisitante,Volumen, file_name,continuo, load_date)  FROM (SELECT  $1,$2,$3,$4,$5,$6,$7,METADATA$FILENAME,''nc'',to_timestamp_ntz(current_timestamp)  from ''@s3_stage/flux/nocontinuo/'' ) pattern=''.*Nocturno_Genero_L.*''  file_format = ''csv_format_flx''  on_error = ''continue'';
				COPY INTO STAGING.ST_FLX_NOCTURNO_MUNICIPIO(Fecha,DiaDeLaSemana,Origen,NombreMunicipio,NombreProvincia,ZonaObservacion,CategoriaDelVisitante,Volumen, file_name,continuo, load_date)  FROM (SELECT  $1,$2,$3,$4,$5,$6,$7,$8,METADATA$FILENAME,''nc'',to_timestamp_ntz(current_timestamp)  from ''@s3_stage/flux/nocontinuo/'' ) pattern=''.*Nocturno_Municipio_L.*''  file_format = ''csv_format_flx''  on_error = ''continue'';
				COPY INTO STAGING.ST_FLX_NOCTURNO_NACIONALIDAD(Fecha,DiaDeLaSemana,Origen,Pais,ZonaObservacion,CategoriaDelVisitante,Volumen, file_name,continuo, load_date)  FROM (SELECT  $1,$2,$3,$4,$5,$6,$7,METADATA$FILENAME,''nc'',to_timestamp_ntz(current_timestamp)  from ''@s3_stage/flux/nocontinuo/'' ) pattern=''.*Nocturno_Nacionalidad_L.*''  file_format = ''csv_format_flx''  on_error = ''continue'';
				COPY INTO STAGING.ST_FLX_NOCTURNO_MES(Mes,EtiquetaDelMes,Origen,ZonaObservacion,CategoriaDelVisitante,Volumen, file_name,continuo, load_date)  FROM (SELECT  $1,$2,$3,$4,$5,$6,METADATA$FILENAME,''nc'',to_timestamp_ntz(current_timestamp)  from ''@s3_stage/flux/nocontinuo/'' ) pattern=''.*Nocturno_Mes_L.*''  file_format = ''csv_format_flx''  on_error = ''continue'';
				COPY INTO STAGING.ST_FLX_NOCTURNO_MES_EDAD(Mes,EtiquetaDelMes,Origen,Edad,ZonaObservacion,CategoriaDelVisitante,Volumen, file_name,continuo, load_date)  FROM (SELECT  $1,$2,$3,$4,$5,$6,$7,METADATA$FILENAME,''nc'',to_timestamp_ntz(current_timestamp)  from ''@s3_stage/flux/nocontinuo/'' ) pattern=''.*Nocturno_Mes_Edad_L.*''  file_format = ''csv_format_flx''  on_error = ''continue'';
				COPY INTO STAGING.ST_FLX_NOCTURNO_MES_GENERO(Mes,EtiquetaDelMes,Origen,Genero,ZonaObservacion,CategoriaDelVisitante,Volumen, file_name,continuo, load_date)  FROM (SELECT  $1,$2,$3,$4,$5,$6,$7,METADATA$FILENAME,''nc'',to_timestamp_ntz(current_timestamp)  from ''@s3_stage/flux/nocontinuo/'' ) pattern=''.*Nocturno_Mes_Genero_L.*''  file_format = ''csv_format_flx''  on_error = ''continue'';
				COPY INTO STAGING.ST_FLX_NOCTURNO_MES_MUNICIPIO(Mes,EtiquetaDelMes,Origen,NombreMunicipio,NombreProvincia,ZonaObservacion,CategoriaDelVisitante,Volumen, file_name,continuo, load_date)  FROM (SELECT  $1,$2,$3,$4,$5,$6,$7,$8,METADATA$FILENAME,''nc'',to_timestamp_ntz(current_timestamp)  from ''@s3_stage/flux/nocontinuo/'' ) pattern=''.*Nocturno_Mes_Municipio_L.*''  file_format = ''csv_format_flx''  on_error = ''continue'';
				COPY INTO STAGING.ST_FLX_NOCTURNO_MES_NACIONALIDAD(Mes,EtiquetaDelMes,Origen,Pais,ZonaObservacion,CategoriaDelVisitante,Volumen, file_name,continuo, load_date)  FROM (SELECT  $1,$2,$3,$4,$5,$6,$7,METADATA$FILENAME,''nc'',to_timestamp_ntz(current_timestamp)  from ''@s3_stage/flux/nocontinuo/'' ) pattern=''.*Nocturno_Mes_Nacionalidad_L.*''  file_format = ''csv_format_flx''  on_error = ''continue'';
				COPY INTO STAGING.ST_FLX_RECURRENCIA(Fecha,DiaDeLaSemana,Origen,ZonaObservacion,CategoriaDelVisitante,Recurrencia,Volumen, file_name,continuo, load_date)  FROM (SELECT  $1,$2,$3,$4,$5,$6,$7,METADATA$FILENAME,''nc'',to_timestamp_ntz(current_timestamp)  from ''@s3_stage/flux/nocontinuo/'' ) pattern=''.*Recurrencia_L.*''  file_format = ''csv_format_flx''  on_error = ''continue'';
				COPY INTO STAGING.ST_FLX_RECURRENCIA_MUNICIPIO(Fecha,DiaDeLaSemana,Origen,NombreMunicipio,NombreProvincia,ZonaObservacion,CategoriaDelVisitante,Recurrencia,Volumen, file_name,continuo, load_date)  FROM (SELECT  $1,$2,$3,$4,$5,$6,$7,$8,$9,METADATA$FILENAME,''nc'',to_timestamp_ntz(current_timestamp)  from ''@s3_stage/flux/nocontinuo/'' ) pattern=''.*Recurrencia_Municipio_L.*''  file_format = ''csv_format_flx''  on_error = ''continue'';
				COPY INTO STAGING.ST_FLX_RECURRENCIA_NACIONALIDAD(Fecha,DiaDeLaSemana,Origen,Pais,ZonaObservacion,CategoriaDelVisitante,Recurrencia,Volumen, file_name,continuo, load_date)  FROM (SELECT  $1,$2,$3,$4,$5,$6,$7,$8,METADATA$FILENAME,''nc'',to_timestamp_ntz(current_timestamp)  from ''@s3_stage/flux/nocontinuo/'' ) pattern=''.*Recurrencia_Nacionalidad_L.*''  file_format = ''csv_format_flx''  on_error = ''continue'';

		END;

		ALTER TASK STAGING.LOAD_FLX_NOCONTINUO RESUME;

        RETURN ''Create task STAGING.LOAD_FLX_NOCONTINUO & RESUME'';

    END;
';




*/


EXECUTE IMMEDIATE '
    BEGIN

                create or replace task STAGING.LOAD_FLX_CONTINUO
                        schedule=''USING CRON  0 11 * * * Europe/Madrid''
                        USER_TASK_MANAGED_INITIAL_WAREHOUSE_SIZE=''XLARGE''
                        as BEGIN
                                COPY INTO ST_FLX_SALIDA_NACIONALIDAD(Fecha,DiaDeLaSemana,Origen,Pais,ZonaObservacion,CategoriaDelVisitante,Volumen, file_name,continuo, load_date)  FROM (SELECT  $1,$2,$3,$4,$5,$6,$7, METADATA$FILENAME,'c',to_timestamp_ntz(current_timestamp)  from '@s3_stage/flux/continuo/' ) pattern='.*Salida_Nacionalidad_202.*'  file_format = 'csv_format_flx'  on_error = 'continue';
                        END;

                ALTER TASK STAGING.LOAD_FLX_CONTINUO RESUME;

                RETURN ''Create task STAGING.LOAD_FLX_CONTINUO & RESUME'';

END;


EXECUTE IMMEDIATE '
    BEGIN

                create or replace task DEV_TOURISM_DB.STAGING.LOAD_FLX_NOCONTINUO
                        schedule=''USING CRON  0 11 * * * Europe/Madrid''
                        USER_TASK_MANAGED_INITIAL_WAREHOUSE_SIZE=''XLARGE''
                        as BEGIN
                            COPY INTO ST_FLX_SALIDA_NACIONALIDAD(Fecha,DiaDeLaSemana,Origen,Pais,ZonaObservacion,CategoriaDelVisitante,Volumen, file_name,continuo, load_date)  FROM (SELECT  $1,$2,$3,$4,$5,$6,$7,METADATA$FILENAME,'nc',to_timestamp_ntz(current_timestamp)  from '@s3_stage/flux/nocontinuo/' ) pattern='.*Salida_Nacionalidad_L.*'  file_format = 'csv_format_flx'  on_error = 'continue';
                        END;

                ALTER TASK STAGING.LOAD_FLX_NOCONTINUO RESUME;

                RETURN ''Create task STAGING.LOAD_FLX_NOCONTINUO & RESUME'';

END;
